### ISSUE TITLE
[Editorial] Images Concepts page name

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wai-tutorials#178]
I wonder if the title of the tutorial should be 'Image Concepts and Accessible solutions' or similar? This is largely because each of the image use cases on the image home page outlines a use case and an approach to dealing with it in a way that is accessible. So the title 'Image Concepts' seems to fall short of the full purpose of the page.

Unless we think that having the a11y solution within the tutorial is already implicit (it could be said)..

**Comment by yatil** [comment]
I think as those are explicit “Accessibility Tutorials”, I personally don’t think that we need the addition of “Accessible solutions”. I’ll see what EO WG thinks about this.

**Comment by yatil** [comment]
EO WG agreed that this is not necessary

**Comment by joshueoconnor** [comment]
Good stuff - thanks
