### ISSUE TITLE
Question about current page with span tag

### ISSUE THREAD

**Issue by lionel-m** [w3c/wai-tutorials#190]
Hi,

[In this example](http://www.w3.org/WAI/tutorials/menus/styling/#indicating-the-current-page) we pass directly from the link "Shop" to the link "MarsCars" using the tab. That is logical, but how can we read the description "Current Page: SpaceBears" in this context with a screen reader? Should we add `tabindex="0"` to the `span` tag?

**Comment by yatil** [comment]
Grüezi Lionel,

If you want a screen reader user to access the link you could use `tabindex="0"` or, afaik, use an `<a>` element without `href` (which will inherit :hover and :focus styles). I think I’d prefer the `tabindex` solution.

**Comment by yatil** [comment]
I will add a note to the tutorial.

**Comment by lionel-m** [comment]
Thank you :+1:
