### ISSUE TITLE
The words Example 1, 2, 3 etc appear to be generated CSS background images, 

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-tutorials#191]
They are not text
a screen reader won't know what example is which.

If we want to use JavaScript to count examples and auto generate that is fine, but I think they should be inserted into the html layer as text.

**Comment by yatil** [comment]
Hi @DavidMacDonald,
we use CSS counters and generated content for that, but I agree that browser’s and AT’s lacking support is a major pain point. That’s why I have reimplemented the behavior using JavaScript.

Best, Eric
