### ISSUE TITLE
Add more detailed SVG examples

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#192]
see [this article](http://www.sitepoint.com/tips-accessible-svg/) for possible examples.

**Comment by melodyma** [comment]
I concur!

**Comment by sharronrush** [comment]
Does "wishlist" mean this is not happening now?

**Comment by yatil** [comment]
@sharronrush Yes. We need to first complete every issues with the current content before starting to create new content, as was outlined in the [short-term goals](http://www.w3.org/mid/8D87B3DD-3B10-4E2B-ABC8-D9D218A14107@w3.org). Otherwise we get in a never-ending feedback loop without ever having a stable version first. We just need to prioritize.

**Comment by yatil** [comment]
@sharronrush Addendum: Of course, if someone would want to work on it right now, that would be great, but completing what we have has priority for me as the resource manager.
