### ISSUE TITLE
Comments submitted to WCAG working Group survey

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-tutorials#234]
To give a head's up for tomorrows WCAG call... here are my comments. Perhaps these issues can be fixed by tomorrow to make the call go smoother. If you would like me to do an inline pull request I can probably do that.

I'm still uncomfortable with the some lines of the Math section. It is a huge topic and it is in great flux. I think Math warrants its own section, which perhaps cannot be done in this project. If Math cannot get its own section, we need to be careful about how we present math in images. I think the opening line is not taking the industry where it needs to go.

>Math expressions are often displayed as images because of the difficulty of presenting equations and special math symbols with HTML. The image below displays a recurring ..."

I think I'm channeling Sina Bahram, with whom I'll be presenting Math at CSUN, in saying that it would be better to rewrite this important opening sentence something like this.

>Historically, math expressions have often been presented as images because of the difficulty of presenting equations and special math symbols with HTML. However, MathML is emerging as the normative presentation of accessible math on the web. If images of math are used, here are some suggestions to improve accessibility. The image below displays a recurring ...

http://www.w3.org/WAI/tutorials/forms/labels/
> HTML allows form fields to be associated with more than one label.

seems like it might be a typo that should be something like:

> HTML //does  not// allow  form fields to be associated with more than one label (unless wai aria is used). ?

http://www.w3.org/WAI/tutorials/forms/instructions/
The CSS class name that has been chosen, class="visuallyhidden" I think is going to get confused with "visibility: hidden",  two very different renderings in AT, which we spend a lot of time educating. Consider changing the class name such as class="offscreen" or add a line to clarify difference where the two are juxtaposed in the same sentence.

http://www.w3.org/WAI/tutorials/forms/instructions/
Approach 1
`<label for="expire">Expiry date:</label> <input type="text" name="expire" id="expire"> <span>(MM/YYYY)</span>`

I mentioned in the last call I don't think we should have an example of instructions not associated with the corresponding field, especially the Approach 1.

`<label for="expire">Expiry date:</label> <input type="text" name="expire" id="expire" aria-describedby="p1"> <span tabindex="-1" id="p1">(MM/YYYY)</span>`

Approach 2 will not read the main label because the aria-labelledby will take over the ACCNAME in the API. This is not an accessible example!

`<label for="expire">Expiry date:</label>
<span>
	<input type="text" name="expire" id="expire" aria-labelledby="expDesc">
	<span id="expDesc">MM/YYYY</span>
</span>`

It should be like this:

`<label id="p2e" for="expire">Expiry date:</label>
<span>
	<input type="text" name="expire" id="expire" aria-labelledby="p2e expDesc">
	<span id="expDesc">MM/YYYY</span>
</span>`
See accessible name calculation for ARIA and 
http://www.w3.org/TR/wai-aria/roles section 5.2.7
Using Aria in HTML
http://www.w3.org/TR/aria-in-html/#aria-labelledby-and-aria-describedby

Placeholder text
"Refer to the techniques described in Hidden labels in cases where you want to avoid redundancy of (visible) labels and placeholder text. <add>Another approach for to save screen real estate is to use JavaScript make them appear (in an associated label tag) above or beside the input that has focus."

http://www.w3.org/WAI/tutorials/forms/validation/
"Forms frequently include required input that needs to be clearly highlighted using labels."
The word "highlighted" is a specific word for form fields which will confuse developers. Consider the word "identified" instead.
"Forms frequently include required input that needs to be clearly identified using labels."

http://www.w3.org/WAI/tutorials/forms/notifications/
The popup modal dialogue example does not show visible focus of the OK and Exit button... fails 2.4.7

http://www.w3.org/WAI/tutorials/forms/grouping/
Add a few bullets to the list:
*Do not nest a fieldsets inside another fieldset
*Reserve fieldset/legends for small groups of controls. For large groups of controls chose a heading instead.

NOTE: Most radio groups will require a fieldset and legend.

Listing errors at the top of the page secitons
 after "Include an in-page link to the corresponding form control to make access easier for the users.":
Add a bullet
"Associate all error messages with their corresponding form fields using aria-describedby"

http://www.w3.org/WAI/tutorials/forms/notifications/
Place tabindex="-1" on all span tags referenced by aria-describedby or by aria-labelledby when it has more than one reference
see explanation here
http://www.w3.org/TR/aria-in-html/#aria-labelledby-and-aria-describedby 

http://www.w3.org/WAI/tutorials/forms/multi-page/
The green progress bar is still shimmering in several browsers.

Contibutors: HTML5 Boilerplate and the Education and Outreach Working Group (EOWG)
For the contributors section let's add the WCAG Working Group, and also fix the typo in the word "Contributors"

**Comment by yatil** [comment]
Hi David, you have had a look at www.w3.org/WAI/tutorials. The updates are on http://w3c.github.io/wai-tutorials/ – I will have  a look at the individual comments tomorrow.

(BTW: Usually it is better to submit issues individually so they can be addressed more easily.)

**Comment by yatil** [comment]
RE:
> http://www.w3.org/WAI/tutorials/forms/labels/
> > HTML allows form fields to be associated with more than one label.
>
> seems like it might be a typo that should be something like:
>
>> HTML //does  not// allow  form fields to be associated with more than one label (unless wai aria is used). ?

Indeed HTML does allow this. you can have one `<input id="ex">` and use one `<label for="ex">The field name is required.</label>` in the general error message as well as immediately in front of the label, e.g. `<label for="ex">Name:</label>`.

**Comment by yatil** [comment]
> http://www.w3.org/WAI/tutorials/forms/instructions/
> The CSS class name that has been chosen, class="visuallyhidden" I think is going to get confused with "visibility: hidden", two very different renderings in AT, which we spend a lot of time educating. Consider changing the class name such as class="offscreen" or add a line to clarify difference where the two are juxtaposed in the same sentence.

The CSS name `visuallyhidden` stems from [HTML5 boilerplate](https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css#L131) and is a widely recognized class name. Added warning to make that clear in 7e7b0cd41083bb1dc8d580d13f355d3363421b7d.

**Comment by yatil** [comment]
> http://www.w3.org/WAI/tutorials/forms/instructions/
> Approach 1
> `<label for="expire">Expiry date:</label> <input type="text" name="expire" id="expire"> <span>(MM/YYYY)</span>`
> 
> I mentioned in the last call I don't think we should have an example of instructions not associated with the corresponding field, especially the Approach 1.
> 
> `<label for="expire">Expiry date:</label> <input type="text" name="expire" id="expire" aria-describedby="p1"> <span tabindex="-1" id="p1">(MM/YYYY)</span>`

This example has been removed in January, see changelog: https://www.w3.org/WAI/EO/wiki/Tutorials/Forms/2015-01-changes#Form_Instructions_.28medium_changes.29

> Approach 2 will not read the main label because the aria-labelledby will take over the ACCNAME in the API. This is not an accessible example!
> 
> `<label for="expire">Expiry date:</label> <span> <input type="text" name="expire" id="expire" aria-labelledby="expDesc"> <span id="expDesc">MM/YYYY</span> </span>`
> 
> It should be like this:
> 
> `<label id="p2e" for="expire">Expiry date:</label> <span> <input type="text" name="expire" id="expire" aria-labelledby="p2e expDesc"> <span id="expDesc">MM/YYYY</span> </span>`
> See accessible name calculation for ARIA and
> http://www.w3.org/TR/wai-aria/roles section 5.2.7
> Using Aria in HTML
> http://www.w3.org/TR/aria-in-html/#aria-labelledby-and-aria-describedby

This was also addressed in January, see changelog: https://www.w3.org/WAI/EO/wiki/Tutorials/Forms/2015-01-changes#Form_Instructions_.28medium_changes.29

**Comment by yatil** [comment]
> Placeholder text
> "Refer to the techniques described in Hidden labels in cases where you want to avoid redundancy of (visible) labels and placeholder text. Another approach for to save screen real estate is to use JavaScript make them appear (in an associated label tag) above or beside the input that has focus."

I don’t think it is necessary to mention a technique that a) can be implemented in a bad way very easily and b) we don’t have an example for. I also think that such examples are relatively uncommon.

**Comment by yatil** [comment]
> http://www.w3.org/WAI/tutorials/forms/validation/
> "Forms frequently include required input that needs to be clearly highlighted using labels."
> The word "highlighted" is a specific word for form fields which will confuse developers. Consider the word "identified" instead.
> "Forms frequently include required input that needs to be clearly identified using labels."

Fixed in 5f07466deeade12293e17813f357387c22358275.

**Comment by yatil** [comment]
> http://www.w3.org/WAI/tutorials/forms/notifications/
> The popup modal dialogue example does not show visible focus of the OK and Exit button... fails 2.4.7

This is a OS/Browser generated standard `alert()` dialog. In all browsers I tested (Firefox, Safari, Chrome) the only active item (the OK button) is focused and it is visible.

**Comment by yatil** [comment]
> http://www.w3.org/WAI/tutorials/forms/grouping/
> Add a few bullets to the list:
> * Do not nest a fieldsets inside another fieldset
> * Reserve fieldset/legends for small groups of controls. For large groups of controls chose a heading instead.

I don’t know if we can agree with those both statements in all situations, for example I might have a fieldset for the shipping address that has a fieldset with who radiobuttons Mr. & Ms.

Also, what are “large groups of controls”? I can imagine that there are situations where fieldsets are useful with more than a few form fields.

> NOTE: Most radio groups will require a fieldset and legend.

I have added a radio button example: 89a715f23217b0b175c9500ed4fd8aefd6ec0af7

> Listing errors at the top of the page secitons
> after "Include an in-page link to the corresponding form control to make access easier for the users.":
> Add a bullet
> "Associate all error messages with their corresponding form fields using aria-describedby"

I have made an addition to the example: b17df875fae770884cfb2ca7aa1e1bce8370eaad

**Comment by yatil** [comment]
> http://www.w3.org/WAI/tutorials/forms/notifications/
> Place tabindex="-1" on all span tags referenced by aria-describedby or by aria-labelledby when it has > more than one reference
> see explanation here
> http://www.w3.org/TR/aria-in-html/#aria-labelledby-and-aria-describedby 

Hm. The page this page is referring to notes IE4 and IE5, is this still a problem in recent versions of Internet Explorer? We can add a note for this if it is present in IE8+, we just need to be quite specific on the advice.

**Comment by yatil** [comment]
> http://www.w3.org/WAI/tutorials/forms/multi-page/
> The green progress bar is still shimmering in several browsers.

This is the old version, see the new version here: https://w3c.github.io/wai-tutorials/forms/multi-page/#using-the-html5-progress-element

**Comment by yatil** [comment]
> Contibutors: HTML5 Boilerplate and the Education and Outreach Working Group (EOWG)
> For the contributors section let's add the WCAG Working Group, and also fix the typo in the word "Contributors"

I have corrected the embarrassing typo. I will add WCAG WG.

**Comment by yatil** [comment]
> I'm still uncomfortable with the some lines of the Math section. It is a huge topic and it is in great flux. I think Math warrants its own section, which perhaps cannot be done in this project. If Math cannot get its own section, we need to be careful about how we present math in images. I think the opening line is not taking the industry where it needs to go.
>
>>    Math expressions are often displayed as images because of the difficulty of presenting equations and special math symbols with HTML. The image below displays a recurring ..."
>
> I think I'm channeling Sina Bahram, with whom I'll be presenting Math at CSUN, in saying that it would be better to rewrite this important opening sentence something like this.
>
>>    Historically, math expressions have often been presented as images because of the difficulty of presenting equations and special math symbols with HTML. However, MathML is emerging as the normative presentation of accessible math on the web. If images of math are used, here are some suggestions to improve accessibility. The image below displays a recurring ...

I have added the sentence to the page and added another heading to make the two approaches more clear: 461de14b570cfa3cf78698a9278e5098acd41186 (This relates to issue #229)

**Comment by DavidMacDonald** [comment]
>Indeed HTML does allow this. you can have one `<input id="ex">` and use one `<label for="ex">`The field name is required.`</label>` in the general error message as well as immediately in front of the label, e.g. `<label for="ex">Name:</label>`

Just so I'm clear. 
>HTML allows form fields to be associated with more than one label.
The way I'm reading this is that it says in HTML we can have two labels pointing to the same input. For instance, 
`<label for="ex">Name</label>
<label for="ex">Keep it short</label>
<input id="ex" ...>`

It this is what it is saying, I would disagree with this...  http://www.w3.org/TR/html5/forms.html#the-label-element 

That is what aria-labelledby solves.

**Comment by DavidMacDonald** [comment]
>I don’t think it is necessary to mention a technique that a) can be implemented in a bad way very easily and b) we don’t have an example for. I also think that such examples are relatively uncommon.

http://paralympic.ca/
tab into the username. Many of my colleagues are advocating this approach. Many discourage the use of placeholder with an invisible label ... the cognitive task force would not like the disappearing label.

Feel free to grab the code...

**Comment by DavidMacDonald** [comment]
http://davidmacd.com/blog/is-tabindex-required-on-describedby.html
Test results of tabindex=-1  and not in modern broswers... NVDA requires it in IE on two reference labels.

**Comment by yatil** [comment]
RE: placeholder
Looks like I didn’t fully understand your point before, I have added a clarifying sentence: 32ae6b7bd9f739384ea6d6294b2b5be0e460eb9b

**Comment by yatil** [comment]
RE: labelledby & tabindex
Added some advice: 9a112c911aa9d26ec7c0f4ac7fd0e637d08f5ee7
It looks like referencing multiple things from labelledby/describedby does not work at all in VO on MacOS. We need to mention this as well.

**Comment by DavidMacDonald** [comment]
Regarding MACOS and iOs and labelledby and describedby:
I didn't wait long enough. They actually read but by default there is a very long delay of over 5 seconds... this can be fixed in the settings. I've updated my test pages to reflect that.

http://davidmacd.com/blog/is-tabindex-required-on-describedby.html

**Comment by DavidMacDonald** [comment]
http://www.w3.org/WAI/tutorials/forms/notifications/
The popup modal dialogue example does not show visible focus of the OK and Exit button... fails 2.4.7.

>This is a OS/Browser generated standard alert() dialog. In all browsers I tested (Firefox, Safari, Chrome) the only active item (the OK button) is focused and it is visible.

In Chrome there are two controls (Ok & X) and there is no way to toggle them, or put visible focus on X. I'll drop it.

**Comment by DavidMacDonald** [comment]
Call is in about a half hour. 

For me the outstanding issues are:
http://www.w3.org/WAI/tutorials/forms/labels/
>"HTML allows form fields to be associated with more than one label."

**Comment by yatil** [comment]
This is not part of the tutorials anymore.
