### ISSUE TITLE
Page Structure -> Content Structure --> Figures: Inconsistent instructions with Tables tutorial

### ISSUE THREAD

**Issue by melodyma** [w3c/wai-tutorials#284]
The Page Structure --> Content Structure --> Figure section here: http://w3c.github.io/wai-tutorials/page-structure/content/#figures
contains inconsistent instructions from the Tables tutorial on figures (http://w3c.github.io/wai-tutorials/tables/). The Tables one doesn't include `aria-labelled-by`.

**Comment by yatil** [comment]
Probably we shouldn’t have `<table>` in that example (in the structure tutorial) but instead use an image. The table caption is already working as a caption, so using ARIA (in the table tutorial) is not necessary.
