### ISSUE TITLE
Page Structure -> Styling -> Highlight section: Fallback?

### ISSUE THREAD

**Issue by melodyma** [w3c/wai-tutorials#285]
Is there a fallback for highlight that is supported by AT? Also, probably want to mention that the highlight colour should meet accessibility contrast requirements.
http://w3c.github.io/wai-tutorials/page-structure/styling/#highlight-section

**Comment by yatil** [comment]
The only thing that would work would be hidden text or the addition of ARIA, but from what I understand this should be announced by AT at some time. I don’t think it is much worth to point out complicated workarounds for this.

I’ll add a note on contrast requirements.
