### ISSUE TITLE
Page Structure -> In-page Navigation -> Anchors: Outdated information

### ISSUE THREAD

**Issue by melodyma** [w3c/wai-tutorials#286]
The anchors tutorial has outdated information about how anchors are displayed in the WAI tutorials. It says it uses the pilcrow symbol, but it actually uses the share icon now.
http://w3c.github.io/wai-tutorials/page-structure/in-page-navigation/#anchors

**Comment by yatil** [comment]
Thanks, I will fix that. Probably we need to remove this altogether now…
