### ISSUE TITLE
<figure> section, Longdesc not well supported and not a best practice yet

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-tutorials#291]
We should not put `longdesc` into the tutorials examples yet. 
Apple doesn't support, and other support is spotty.
http://davidmacd.com/blog/csun/files/long-description.html
Consider an expand/collapse solution or just putting the long description in the page.

**Comment by DavidMacDonald** [comment]
PS out of 26 AT voting specialists at CSUN, none put their hand up for it.

**Comment by jnurthen** [comment]
"PS out of 26 AT specialists at my CSUN showdown, none put their hand up for longdesc."
I seem to recall your example didn't really need a description so I'm not sure that is conclusive.

**Comment by yatil** [comment]
[Here](http://w3c.github.io/wai-tutorials/page-structure/content/#figures) (I assume you mean that section), the figure is **not** used to denote the long description but to show the image as a figure related to the text, like it is common in text books (diagrams in physics for example). Thus the longdesc question doesn’t apply.

I have added a separate link to the longdesc as we’re recommending in the images tutorial to make clear that it can’t be used without one.
