### ISSUE TITLE
Consider expand/collapse as primary long description mechanism

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-tutorials#292]
http://w3c.github.io/wai-tutorials/images/complex/

Consider the CSUN votes, and order the examples accordingly. Start off with an expand/collapse details summary with javascript polyfill... I have an example from Jason Kiss and Steve Faulkner linked below.
The longdesc attribute was never well implemented in the mainstream, and browser support and AT support  was inconsistent.It was deprecated in HTML5  but it is now an extension. A void existed for a viable replacement and WCAG still required a long description be provided for complex images.  Contenders are:

    1. Simple link on page to a long description (5 Votes)
    2. In page descriptions referred to in the image alt, (1 Vote)
    3. The html5 figure element wrapped around the image and it’s long description (0 Votes)
    4. Expandable collapsible link used to hide the description on the page. (20 Votes -Winner)
    5. Longdesc (0 Votes)

I understand that there is an a11y supported box beside it, but it should not be the first recommendation. 

An example and the code used is here as well as more accessibility support results.
http://davidmacd.com/blog/csun/files/long-description.html

**Comment by yatil** [comment]
We have discussed that at length before CSUN in WCAG and EO working groups and agreed to this solution. We propose a simple link to the long description in addition to the longdesc (wasn’t asked in your session at CSUN). I personally don’t consider a JavaScript solution as best practice if there are good non-JS solutions. We can reconsider this when the support for HTML5 <details>/<summary> has landed in browsers in an accessible way.
