### ISSUE TITLE
Reference to 200% zoom implies WCAG requires text zoom only

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-tutorials#293]
"The user needs to be able to resize the text to 200% of its size anywhere on the page, without the text being cut off or overlapping other text."

The reference implies WCAG requires text zoom only. WCAG allows browser zoom. SO we'd need to word this as a best practise.

**Comment by WobleDuck** [comment]
I anyone has doubts about how 1.4.4 is interpreted in general.  1.4.4
means: Authors must provide inadequate enlargement in an unusable format.

**Comment by DavidMacDonald** [comment]
I would love that language, but that is not what it says...

**Comment by yatil** [comment]
This references (in my head) to overflow: hidden; situations, not to horizontal scrolling situations.
