### ISSUE TITLE
16px base font size: seems like most web master's would balk at.

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-tutorials#294]
"The px values assume that the root font-size is 16px."

16px is good for low vision, but I don't think its a realistic expectation for corporate or government web sites.

Consider 12px, or maybe 14px

**Comment by WobleDuck** [comment]
16 px doesn't cut it for anyone with low vision.  In fact by definition,
people with low vision cannot read 16px at 16 inches.

**Comment by yatil** [comment]
The trend is going to large font sizes. Examples: Microsoft uses 16px, Apple uses 19px. The default font size in browsers is 16px For the example we need to define what font size the parent element has and 16px is a value that allows us to easy to calculate the resulting font size.
