### ISSUE TITLE
fly out menu: issue when multiple submenus

### ISSUE THREAD

**Issue by ffoodd** [w3c/wai-tutorials#305]
When multiple submenus are present, quickly hovering on submenus makes them open but on mouseout, all timeouts are cancelled so the next open submenu stays opened until next mouseout on it or a click event.

I made [a pen](http://codepen.io/ffoodd/full/raEGoK/) based on the flyoutaria example.

Am I missing something?

**Comment by yatil** [comment]
Hi!
If you have multiple drop downs you’d either need another timeout _or_ register how what menus open at which time. As these are examples to demonstrate the principles, the details are left to the readers ;-)

Cheers,
Eric

**Comment by ffoodd** [comment]
Hi Eric,

Thank you for the answer :)
