### ISSUE TITLE
Translate the document

### ISSUE THREAD

**Issue by brunopulis** [w3c/wai-tutorials#328]
Hi to everyone.

There is a plan to translate the project?

**Comment by yatil** [comment]
There are no concrete plans yet, what language would you like to have the tutorials in?

**Comment by brunopulis** [comment]
@yatil Brazilian Portuguese.

**Comment by yatil** [comment]
Closing, translations are now tracked in the wiki: https://github.com/w3c/wai-tutorials/wiki/Translations
