### ISSUE TITLE
Required Fields 2 Problems

### ISSUE THREAD

**Issue by WayneEDick** [w3c/wai-tutorials#329]
1) The errors are indicated by a "red" border. Seems to violate 1.4.1
2) The time and date fields don't indicate error.

Wayne

PS. Question: Why do you use `<div>` in `<div>` for code and just `<div>` in the example?.

**Comment by yatil** [comment]
Hi Wayne,

1. The errors are indicated by the browser, the author of the website has little to no influence on how it is displayed. It should also be marked as invalid to accessibility APIs.
2. As said, that depends on the support in the browser used.

Re: PS: The two divs in the source code help with the design layout, they are not necessary.
