### ISSUE TITLE
why put the longdesc method as first approach?

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/wai-tutorials#330]
Using longdesc may be viewed by some as the most theoretically elegant method of providing a long description for an image, but it is the least robust of the methods listed. 
http://www.w3.org/WAI/tutorials/images/complex/#providing-a-link-to-the-long-description-via-longdesc

Suggest moving to  last and also styling/labelling accessibility support info as a warning.

question: 

"In Firefox, long descriptions linked by longdesc are available to all users through “View description” in the image’s context menu. "

How does a keyboard only user access the long description?

**Comment by amandarush** [comment]
Given that browser support is less than optimal for longdesc, I don't believe listing it as the first, (and therefore, perceived optimal) method for handling image descriptions is the best approach, and so am agreeing with @stevefaulkner that it should be listed last.

**Comment by sharronrush** [comment]
Thanks Steve and Amanda for your observations and comments.  EOWG tends to agree but unfortunately we have no active editor for this resource at this time.  We expect to have some cycles to devote early in Q2 2016 so have placed your suggestion in the work queue to be addressed at that time.  Thanks again your comments.

**Comment by stevefaulkner** [comment]
@sharronrush I have created a pull request https://github.com/w3c/wai-tutorials/pull/331 that udpates with suggested chnages.

**Comment by sharronrush** [comment]
Hi Steve,  first thanks again for providing such useful support for your suggested change. EO has now been assigned to review the issue and consider approval of the pull request.  As part of the review, we are looking back at previous discussions, especially the impact on users with low vision.  If you are interested in those, they are found in <a href="http://www.w3.org/2015/01/30-eo-minutes#item04">EO minutes of 30 Jan</a> and <a href="http://www.w3.org/2015/02/06-eo-minutes.html#item08">EO minutes of 06 Feb</a>. Let me know if you want to attend any of the discussion of the issue we will have during the first weeks of December.  In any case, I will keep you posted. Thanks again.

**Comment by stevefaulkner** [comment]
Thanks Sharron, the links to discussions you provided are illuminating and
useful.

--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by slhenry** [comment]
resolved https://github.com/w3c/wai-tutorials/pull/334
