### ISSUE TITLE
Summary attribute

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-tutorials#337]
from Twitter https://twitter.com/oscarcao/status/678778789296377856
@w3c_wai interesting you guys still recommending to use summary attribute in your tuts, even tho it's obsolete.

**Comment by yatil** [comment]
We did add it as it is still recommended if people are writing HTML4 documents. I don't really think we need it, but the group thought otherwise when we wrote the tutorial, that notion might have changed.

**Comment by yatil** [comment]
Find here the [relevant part of the tutorial](http://www.w3.org/WAI/tutorials/tables/caption-summary/#using-the-summary-attribute) which mentions the summary as a fourth approach while mentioning three other approaches first that are not made obsolete. Here is the [relevant part of the HTML5 spec](http://www.w3.org/TR/html/obsolete.html#attr-table-summary) which links to [4.9.1.1 Techniques for describing tables](http://www.w3.org/TR/html/tabular-data.html#table-descriptions-techniques).
