### ISSUE TITLE
We should consider qualifying the use of Title

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-tutorials#341]
the title attribute does not become visual on keyboard focus. We should show how to do that, or talk about it.

There is some talk about removing or modifying the example in WCAG for this.
https://www.w3.org/TR/WCAG20-TECHS/H33.html

We should consider what JQUERY does or OAA.
https://jqueryui.com/tooltip/
http://oaa-accessibility.org/example/39/

**Comment by yatil** [comment]
I guess this relates to this [section of the forms tutorial](http://w3c.github.io/wai-tutorials/forms/labels/#using-the-title-attribute)? We don’t recommend or even mention title on links in the tutorials, I think.

**Comment by AndrewArch** [comment]
@DavidMacDonald pity the OAA example hasn't attached the labels correctly. But what I was actually wondering is with either JQUERY or OAA, how does JAWS, NVDA or VoiceOver respond - are the 'tips' announced?

**Comment by brianelton** [comment]
Will qualify `title` use while working on w3c/wai-website#609
