### ISSUE TITLE
Menubar example: roles should not have "aria-" prefix

### ISSUE THREAD

**Issue by carmacleod** [w3c/wai-tutorials#347]
This paragraph contains 3 roles that are prefixed with "aria-", but that prefix is not valid for roles.

"...the following roles are used in the example:
aria-menubar: Represents a usually horizontal menu bar.
aria-menu: Represents a set of links or commands in a menu bar, it is used for the fly-out menus.
aria-menuitem: Represents an individual menu item."

It should instead be:
"...the following roles are used in the example:
menubar: Represents a usually horizontal menu bar.
menu: Represents a set of links or commands in a menu bar, it is used for the fly-out menus.
menuitem: Represents an individual menu item."

**Comment by yatil** [comment]
This is already addressed in the Editor’s Draft. We’re working on publishing it asap.

http://w3c.github.io/wai-tutorials/menus/application/
