### ISSUE TITLE
Menubar example: Delete aria-label="functions" in role="menu" ul?

### ISSUE THREAD

**Issue by carmacleod** [w3c/wai-tutorials#348]
On http://w3c.github.io/wai-tutorials/menus/application/
I don't understand the need for the aria-label in the role="menu" element.
`<ul role="menu" aria-label="functions" id="appmenu">`

As far as I can tell, AT ignore this, which is good. If they were to read it, it might just be confusing extra audio.

**Comment by yatil** [comment]
The `aria-label` is not required, but it provides a label that could be used if assistive technologies decide to have users access menus by their names. For example a voice control users might be able to say “Select item file from the functions menu”.

I don’t think it warrants removal, as it is [totally allowed](http://w3c.github.io/aria/aria/aria.html#menu) to do so, but I will check back with the Working Group.

**Comment by carmacleod** [comment]
Ok... but that particular element isn't really a menu... it's actually a menubar... (the fact that it's a menu is just an artifact of issue #349). So maybe voice control users might be able to say “Select item file from the functions menubar”?

**Comment by yatil** [comment]
Good point.

**Comment by carmacleod** [comment]
If it stays in, then it probably merits an explanation in the tutorial write-up.  :)
