### ISSUE TITLE
Menubar example: why is "menubar" on div and not ul?

### ISSUE THREAD

**Issue by carmacleod** [w3c/wai-tutorials#349]
http://w3c.github.io/wai-tutorials/menus/application/

For the following code:

``` html
<div role="menubar">
    <ul role="menu" aria-label="functions" id="appmenu">
```

I think that it would make more sense to remove the extra layer and have the following instead (Note that I also deleted aria-label="functions" because of issue #348):
`<ul role="menubar" id="appmenu">`

Having the extra layer is problematic because that causes NVDA to say "File submenu" and "Edit submenu" when it should just be calling them "File menu" and "Edit menu"; and VoiceOver says "level 3" when the user drops down a menu, instead of "level 2".

I am not sure if the `<ul role="menubar">` markup actually works with all AT/browsers. However, perhaps it should?

**Comment by yatil** [comment]
Hi @carmacleod and thanks for your feedback.

I have to search for the reasoning, but I _think_ it was that the menu item role was not supposed to be a direct child of the menubar role, but it seems to be not the case anymore. We’ll look into it.

**Comment by carmacleod** [comment]
Thanks! Awesome response time!  :)

**Comment by yatil** [comment]
Trust me, you got lucky there ;-)
