### ISSUE TITLE
Menu example: Implement proper tab/shift-tab behavior

### ISSUE THREAD

**Issue by carmacleod** [w3c/wai-tutorials#350]
http://w3c.github.io/wai-tutorials/menus/application/

Using the keyboard, type tab to get to the File menu. Now type tab again, and I was surprised to go to the Edit menu. The APG says that typing tab will go to the next element in the tab sequence. The real problem with this is that the tab key cycles to the File menu again (and shift+tab cycles in the reverse direction) causing the user to be stuck in a keyboard trap in the menu bar.

Here are the relevant words from the menu/menubar section of the ARIA APG:
http://w3c.github.io/aria/practices/aria-practices.html#menu
Tab: Close the menu and all open parent menus and move focus to the next element in the tab sequence.
Shift + Tab: Close the menu and all open parent menus and move focus to the previous element in the tab sequence.
The keyboard behaviors of a menubar are the same as other menus except that a menubar is typically visually persistent so the first item is in the tab sequence and Escape, Tab, and Shift + Tab do not close it.

**Comment by yatil** [comment]
Hi, thanks @carmacleod for your feedback.

It is not a keyboard trap as you can leave the the menu with the escape key. However, I agree that the tab key functionality needs to be implemented correctly.

(I will change the title of the issue to reflect that.)

**Comment by carmacleod** [comment]
Ok, great! Thanks!
