### ISSUE TITLE
Menubar example: Please add at least one submenu

### ISSUE THREAD

**Issue by carmacleod** [w3c/wai-tutorials#352]
The example feels a bit incomplete without at least one submenu. Perhaps the File menu could have "Save As" with Text, RTF, Html. And/or maybe the View menu could have a Full Screen menu item, and then make a Zoom submenu with the 100%, In, and Out.

**Comment by yatil** [comment]
This was mainly done to not make the example too complex – the aim was explicitly not to make a complete ARIA example with all the bells and whistles but to make a clear distinction on when to (not) use the ARIA menu.
