### ISSUE TITLE
Menubar example: Add a separator

### ISSUE THREAD

**Issue by carmacleod** [w3c/wai-tutorials#353]
http://w3c.github.io/wai-tutorials/menus/application/
For completeness, probably want to have at least one separator in this example.
https://rawgit.com/w3c/aria/master/aria/aria.html#separator

(if so, might want to also make sure the "position in set" and "set size" attributes don't count separators...
https://rawgit.com/w3c/aria/master/aria/aria.html#aria-posinset )

**Comment by yatil** [comment]
Good idea, however the idea was to keep the example bare-bones on purpose to not have people using those menus in non-application environments. Also the scope is not to be a full-fledged ARIA tutorial but a WCAG tutorial. Let me check back with @nitedog and the EO Working Group and see if we want to revamp that example. (TBH, I wonder if this can be under the Menu tutorial or if this warrants a multi-page tutorial by itself.)
