### ISSUE TITLE
Menubar example: Only call preventDefault for keys that were consumed

### ISSUE THREAD

**Issue by carmacleod** [w3c/wai-tutorials#355]
In the Menubar example: https://www.w3.org/WAI/tutorials/menus/examples/appmenu/
the "keydown" event listener switches on event.keyCode and then calls event.preventDefault();

You only want to call preventDefault if you handled the key, so probably need to set a flag to true for right, left, tab, enter, down, up, esc, and then only call event.preventDefault(); if the flag is true.

This is because the way the code currently is means that the user cannot type basic browser command keys like ctrl+L or F5 or ctrl++ etc while focus is in the menu bar.

**Comment by yatil** [comment]
Thanks, this is great feedback! :-)

**Comment by carmacleod** [comment]
You're welcome. :)
Just a thought... maybe the example could be shared with the APG people?
Or maybe they could link to it from their APG menu example section as an "additional example" or "WAI Tutorial example" or something?
https://github.com/w3c/aria-practices/issues/110
And once they have their example coded up, you probably want to link to that from your tutorial?
(Anyhow, I guess we'd need to open a meta-issue somewhere for that discussion... it may apply to many?/most?/all? of your tutorial widgets and their patterns - would be nice to have some cross-pollination going on so that accessibility examples are more discoverable.  :)

**Comment by yatil** [comment]
I have a meeting scheduled with the ARIA group on Thursday, to explore thoughts like that. :-)

**Comment by carmacleod** [comment]
Awesome!

**Comment by a11ydoer** [comment]
Hi @carmacleod @yatil 
Jon Gunderson and I are updating menubar examples. https://github.com/w3c/aria-practices/pulls 
I would appreciate your review on this menubar example if you have time. This will be also reviewed in next APG meeting. Thanks in advance.
