### ISSUE TITLE
Review Images tutorial changes

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#356]
Hi @w3c/wai-eo-tutorialistas – lets try to start the work here.

Please review any [open issues and pull requests for the “Update Images Tutorial” milestone](https://github.com/w3c/wai-tutorials/labels/Images%20Tutorial).

It is one really small change, and I’d like your feedback by the end of the milestone’s due date on October 9th.

To Approve the changes, simply reply to the pull request starting a line with “Approved”. If you feel strongly to reject a change, comment with “Rejected” in a similar message.

**Comment by sharronrush** [comment]
Approved

**Comment by yatil** [comment]
I have merged this minor fix.
