### ISSUE TITLE
Misleading link text in the alt decision tree

### ISSUE THREAD

**Issue by TouficS** [w3c/wai-tutorials#358]
Does the image contribute meaning to the current page or context?
… and it shows content that is redundant to real text nearby.
Use an empty alt attribute. See Functional Images. (Should say: Use an empty alt attribute. See Decorative Images.)

**Comment by AndrewArch** [comment]
The linked example is correct ([Logo image within link text](https://www.w3.org/WAI/tutorials/images/functional/#logo-image-within-link-text)), but I can understand why TouficS thought it is incorrect to link to 'Functional Images'. 

Maybe the linked text could become 'redundance functional images'

**Comment by yatil** [comment]
I agree with @AndrewArch – I have just posted a possible fix in the pull request above. Does that address your concerns?

**Comment by yatil** [comment]
^^^ @TouficS
