### ISSUE TITLE
Minor edit proposal on introduction

### ISSUE THREAD

**Issue by dboudreau** [w3c/wai-tutorials#366]
I'd like the focus of our tutorials to be centered on users/people as much as possible, and consequently, that our wording suggests that focus as well. As a result, I'd like the introductory paragraph to be slightly modified, like so:

> "To help users orient themselves on web pages, the content and different areas need to be structured to help assistive technology identify them. This tutorial shows how to use HTML elements and WAI-ARIA attributes to allow users to navigate through the page and engage with the content efficiently."

To:

> "To help people with disabilities orient themselves on the Web, the content and different areas of the pages need to be structured so assistive technology users can easily identify them. This tutorial shows how HTML elements and WAI-ARIA attributes can be used to help people navigate through pages and engage with content efficiently."

**Comment by susanatx** [comment]
I agree we need to focus more on users but I don't see how these changes do. Denis, can you be more specific about the type of language currently used which you think needs improvement?

**Comment by dboudreau** [comment]
@susanatx - It's about little, subtle things like using the word "users", instead of people with disabilities. It's about talking about the expectations of screen readers instead of expectation of people using screen readers. I don't think we should talk about helping assistive technologies do anything. I think we should talk about helping people who use those technologies instead. It's a very subtle difference most people would not even notice, but it completely changes the angle and the perspective, IMHO.

**Comment by yatil** [comment]
I cannot comment in detail (I try to concentrate on the Carousel at the moment), but we didn’t want to write “people with disabilities” instead of “users” to make sure that it is more inclusive and this guidance also covers best practices in general. I guess @nitedog has an opinion (also to #367), too.

**Comment by yatil** [comment]
Hi @dboudreau,

this was already changed a bunch from the published version at w3.org and as I have been madated to work on it now, I will try to incorporate your changes into a new version.

For the current draft, always see the Github version: https://w3c.github.io/wai-tutorials/page-structure/
