### ISSUE TITLE
Additional edits on introduction

### ISSUE THREAD

**Issue by dboudreau** [w3c/wai-tutorials#367]
In the spirit of issue #366, I wanted to suggest some edits to the bulleted list, so they’re all built following the same pattern, and we put more of an emphasis on people than users.

> - Page Sections: Identify and mark section on pages using HTML5 and WAI-ARIA roles to make sure that the purpose of each individual section is conveyed to users.
> - Headings: Convey the page’s structure and sections of content by adding headings of different levels.
> - Content Structure: Mark up content so it can be easily interpreted and adapted to user’s needs.
> - Styling: Apply a distinct hierarchy to the visual page’s design, so users are able to easily determine what each section of the page does.
> - In-page Navigation: Provide navigation aids to help users to get around the page and discover the various sections of the page. Consider adding a “table of content” for longer pieces of content.

**Would become:** 

- Page Sections: Identify page sections using HTML5 markup and WAI-ARIA roles, so the purpose of each section is conveyed to people using assistive technologies.
- Headings: Provide headings of different levels to convey the structure and sections of pages to people using assistive technologies.
- Content Structure: Mark up content so it can be easily interpreted and adapted to various user’s needs.
- Styling: Apply a distinct visual hierarchy to the design of pages, so users can easily determine the purpose of each section.
- In-page Navigation: Provide navigation aids to help people using assistive technologies get around the page and discover its various sections. Consider adding a “table of content” for longer pieces of content.

**Comment by yatil** [comment]
A bit like in #366 – I see what you want to do, but just replacing users with “people using assistive technologies” does not do it for me. In this case it a) becomes a bit repetitive and b) is not including all the other users that are not using assistive technologies. I think I’ll close this issue but keep it in the back of my head to make the tutorials more people-centric.

**Comment by dboudreau** [comment]
> but keep it in the back of my head to make the tutorials more people-centric.

Fair enough. My work here is done then. ;)
