### ISSUE TITLE
Page Structure Concepts Intro

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-tutorials#376]
Great clarity in section summaries, suggested rewrite below:

1. Page Regions: Identify content sections using HTML5 and WAI-ARIA roles.
2. Headings: Add different level heading and nest them logically to label sections of content according to their relationships and importance.
3. Content Structure: Use semantic qualities of elements appropriately and meaningfully.
4. Styling:  Use consistent styling to allow users to keep track of their position in the web page and of what is important on the page.  (**Note - I can't suggest anything here because I am not clear about what you are trying to say**)
5. In-page Navigation: Provide mechanisms that allow direct navigation between sections of a web page.

**Comment by yatil** [comment]
Thanks! Used some of the wording in 16015e052941eaa342743f534fa51d98b1e124c7.
