### ISSUE TITLE
Focus management after form submit with errors

### ISSUE THREAD

**Issue by cyberseraphic** [w3c/wai-tutorials#387]
https://www.w3.org/WAI/tutorials/forms/notifications/#after-submit

Referring to this section, I'd like to request if some consideration could be given to describing focus management after submitting a form with fields containing errors? I believe best practice involves giving focus to the first form field that is in error, but I could be mistaken. At least some discussion of the issue would be appreciated.

**Comment by yatil** [comment]
Hi @cyberseraphic,

thanks for the feedback. I, too, think this is best practice for forms with multiple fields. I’ll make sure to get this in the next update to the forms tutorial.
