### ISSUE TITLE
Under Announce the Current Item (Carousel Functionality) 

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-tutorials#388]
> Do not move keyboard focus to the new current item when the carousel changes automatically, to not draw away the user from other parts of the web page each time the items change. 

This sentence seems confusing, specifically "to not draw away the user..."  I think its saying make keyboard focus sticky when the carousel changes automatically so that the user does not lose her place when items change.  Is that correct?

**Comment by yatil** [comment]
I think the gist is to not move the focus around when automatic changes occur. I will try to simplify this before publication.

**Comment by sharronrush** [comment]
I agree with @lakeen and have this suggestion:

CURRENT: Do not move keyboard focus to the new current item when the carousel changes automatically, to not draw away the user from other parts of the web page each time the items change.

SUGGESTED: Allow the user to maintain control of the keyboard focus. This means that when the carousel advances automatically, users should not be drawn away from their current place in the page to focus on the new current carousel item.

**Comment by yatil** [comment]
Thanks for the great suggestion, @sharronrush! I’ve changed it.
