### ISSUE TITLE
[Carousel Concepts] Add general usability warning to the page

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-tutorials#389]
While I agree we should have this tutorial as many people will want to implement one, and if they do it should be accessible, the usability community seems to general recommend they not be used these days, or be used with caution. Eg

- http://shouldiuseacarousel.com/

- https://www.smashingmagazine.com/2016/07/ten-requirements-for-making-home-page-carousels-work-for-end-users/

- http://numiko.com/blog/pros-and-cons-carousel

So, wondering if we should advise against them too in some small way?

**Comment by yatil** [comment]
I wonder what @nitedog and the rest of the @w3c/wai-eo-planning team are thinking.

**Comment by sharronrush** [comment]
Eric, this is something that had occurred to me as well. Carousels are not highly recommended and have come to be regarded as the current version of scrolling ticker tapes, widely discouraged. Evidently marketing research shows that they are not very effective as messaging vehicles either. But the fact remains that they are ubiquitous. If they are done, they should at least be done with accessibility issues addressed in someway.  So I think Andrew's point is well worth considering. It is likely that we should add a general nudge against carousels at all with the message "but if you must do so, here is how to do it right..."

**Comment by bakkenb** [comment]
I agree some discussion is needed.

Although usually implemented in an inaccessible way, carousels are still used all over the web. We need to provide guidance on implementing them accessibly. 

If accessible implementation is achieved, are there still usability issues? I am not convinced by these articles that if made accessible, carousels still should not be used. Many of the issues that are brought up would be alleviated with accessible implementation, or they are not really about accessibility.

**Comment by yatil** [comment]
How do we provide a good overview of the usability and discoverability aspects without making this a big part of the tutorial? I don’t want to say “Carousels are bad for usability and discoverability, but if you need to implement them anyway, do it like this…” and leave them hanging with the need to research the topic. We either need to link out to some secondary information or address the issue differently.

**Comment by nitedog** [comment]
I don't think this is a showstopper. I will try a pull request for the overview page later today to help address this important point.

**Comment by yatil** [comment]
@AndrewArch, @nitedog, @sharronrush @bakkenb – I have drafted a first idea in 5894ebe1b6203ffb9658ecb6b526d7a32c25620a, a preview can be seen at https://w3c.github.io/wai-tutorials/carousels/#what-are-the-key-points

I am not sure where to link, if we want to link, but at least that’s a start for a discussion :-)

**Comment by nitedog** [comment]
I was thinking of a similarly concise approach but think that saying "research shows" and linking to only one source is problematic, unless this is widely accepted research. I don't believe this source is widely recognized.

I suggest slight rewording:

Note: Carousels are disputed from usability perspective because their content can be hard to discover for some. Ensuring accessibility can improve the usability too.

This note could also move up in the page, maybe under "What are carousels" but not sure.

**Comment by bakkenb** [comment]
Thanks for pulling something together as a start for us to react to Eric.

Agree with Shadi's statement that the wording needs to be changed. And possibly calling it out a bit more. The location of it seems fine to me.

**Comment by yatil** [comment]
I have changed the wording to @nitedog’s much better wording, I also made “Note:” bold to call it out a bit more.

Putting it under “What are carousels” was my fist idea, but then I wondered if it would look funny to have one paragraph explaining what it is, and another similarly long paragraph warning from using it. Also I wondered if people would overlook the paragraph there if they already knew what carousels are.

**Comment by nitedog** [comment]
Yes, I was wondering about that too. It's fine where it is now. But here a suggested edit to my suggested edit:

Note: Carousels are disputed from usability perspective because their content can be hard to discover. Ensuring accessibility improves usability too.

**Comment by bakkenb** [comment]
I like it... just a small tweak in two areas (100% for editors' discretion).

**Current:** Carousels are disputed from usability perspective because their content can be hard to discover. Ensuring accessibility improves usability too.

**Recommended:** Carousels are disputed from [a] usability perspective because their content can be hard to discover. Ensuring accessibility [also] improves usability.

**Comment by yatil** [comment]
* @bakkenb: +1 to adding the “a”
* @bakkenb & @nitedog: I wondered about the second sentence anyway. For me it is promising a bit too much. I wondered if we could go with “Ensuring accessibility can also improve usability.”

**Comment by nitedog** [comment]
fine with me, great suggestions brent!

**Comment by bakkenb** [comment]
+1 to the last change Eric. Good catch!

**Comment by yatil** [comment]
I’ve made the changes and I’m happy to close the issue if @AndrewArch finds the change sufficient.

https://w3c.github.io/wai-tutorials/carousels/#what-are-the-key-points

**Comment by AndrewArch** [comment]
Excellent work team :)
