### ISSUE TITLE
[Carousels - Styling] add number in left navigation

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-tutorials#396]
This page seems as important as any of the other content pages - structure, functionality, and animations. I think it should have a number and be listed in the same way in the left navigation.

**Comment by Ryladog** [comment]
+1

 

​​​​​* katie *

 

Katie Haritos-Shea 
Principal ICT Accessibility Architect (WCAG/Section 508/ADA/AODA)

 

Cell: 703-371-5545 |  <mailto:ryladog@gmail.com> ryladog@gmail.com | Oakton, VA |  <http://www.linkedin.com/in/katieharitosshea/> LinkedIn Profile | Office: 703-371-5545 |  <https://twitter.com/Ryladog> @ryladog

NOTE: The content of this email should be construed to always be an expression of my own personal independent opinion, unless I identify that I am speaking on behalf of Knowbility, as their AC Rep at the W3C - and - that my personal email never expresses the opinion of my employer, Deque Systems.

**Comment by yatil** [comment]
Hi you two!

I have removed the number because the styling applies to the carousel overall, I did not want to have it look as “Step 4” – However I see your point, and I think I will discuss that in EO and see what the group thinks about it. I’m personally not feeling strongly.

**Comment by bakkenb** [comment]
I agree with @nitedog on this one. Styling is called out in the "[Carousel Concepts](https://w3c.github.io/wai-tutorials/carousels/)" page in a list with the other three, so it is already part of that group. It should be treated the same in the navigation and be listed as #4. 

---
> I did not want to have it look as “Step 4”

Personally, I didn't really see the numbers 1-3 in the navigation as steps, so I wouldn't have interpreted this as step 4 in a series of steps.

**Comment by yatil** [comment]
OK, good for me.
