### ISSUE TITLE
[Carousels Functionality] minor text edit

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-tutorials#399]
Shouldn't "support by assistive technologies" be instead "support for assistive technologies"

**Comment by bakkenb** [comment]
I think so.

Also in the same paragraph...  Shouldn't "Use <button> elements provide semantic meaning" be instead "Use <button> elements **to** provide semantic meaning"

**Comment by bakkenb** [comment]
And drop the work "anyway" from the end of the final sentence in that paragraph.
