### ISSUE TITLE
Additional links to working example

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-tutorials#404]
I think it would be helpful to have an additional link to "working example." Perhaps under the first code example on each page of this tutorial.

**Comment by yatil** [comment]
Interesting idea, maybe we can think about how to implement it in an unobtrusive way somehow. I think a “see this code in the full code example” link would indeed be useful. Unfortunately it is not possible to link to individual lines in the code with the tech we currently use.

**Comment by AndrewArch** [comment]
Good idea Howard - the obvious place for such a link would seem to be just before the "Related WCAG 2.0 resources" section

**Comment by yatil** [comment]
@AndrewArch On each page? I mean we already have the link to the working example in the main navigation.

**Comment by dboudreau** [comment]
Was the "working example" link in the menu on the left recently added? If so, does that fix this issue, or are we considering additional links on top of that one?

**Comment by AndrewArch** [comment]
@yatil probably, as people scroll down and miss the tutorial navigation
