### ISSUE TITLE
Menus - Fly-out Menus - for dexterity 

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-tutorials#407]
Some people have trouble operating fly-out menus, especially people with tremors, limited fine motor dexterity, etc. (disclosure: including myself)

Is there any reason not to suggest that menus are available in a non-fly-out option -- that is, if one clicks on the top menu item, it goes to a page with all the sub-links not-fly-out?

**Comment by yatil** [comment]
Good point, @slhenry – I thought we had that in there, but it might have gotten lost when we restructured the tutorial. I’ll add a sentence or two.

**Comment by shwetank** [comment]
Regarding "fly-out" menus : The more prevalent term I have heard is "drop-down" menus, so maybe we could mention that term here too? Just for some extra clarity.

**Comment by yatil** [comment]
@shwetank: Good catch, I have opened a new issue for this: #413 :-)
