### ISSUE TITLE
Carousels Concepts: “What are the key points?” heading

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#408]
During Kris Anne’s copyedit run, she changed 

> What are the key points?

to 

> How can carousels be accessible?

I find that this is not 100% capturing the section after the heading. I can think of something like…

* (What are the) (Key) Aspects of making carousels accessible(?)

I don’t have any particularly bright ideas for this at the moment.

**Comment by sharronrush** [comment]
What about "what are the basic issues"

**Comment by iamjolly** [comment]
perhaps: "Essential Aspects for Accessibility"

**Comment by nitedog** [comment]
What are the reasons for this suggestion? I prefer the way it is now - Key Points.

**Comment by yatil** [comment]
@nitedog, from the [Feb 27 Minutes](https://www.w3.org/2017/01/27-eo-minutes.html#item01):

> KrisAnne: My rationale was that we had a what and a why as previous headings and so I was looking for the how which is why I proposed what I did.

(Sorry for not including this earlier.)

**Comment by AndrewArch** [comment]
"what makes [them/carousels] accessible"
"how to [solve/address] carousel accessibility"

**Comment by lakeen** [comment]
I tend to agree with @nitedog 
or what about:
"What are the concerns for accessibility?"

**Comment by hkramer** [comment]
How about: "What is required for [carousel] accessibility"?
or 
"What are the key accessibility issues"?

**Comment by bakkenb** [comment]
I do think the title needs to be adjusted. The current one just doesn't fit well.
I prefer the two that @AndrewArch came up with, mostly "what makes carousels accessible."

**Comment by yatil** [comment]
I mildly think that “What makes carousels accessible?” is too general, but it looks like it could emerge as consensus. The question is if it is really much better than “What are the key points?”.

**Comment by AndrewArch** [comment]
[The question is if it is really much better than “What are the key points?”.] - good point!

My suggestions were just that - suggestions :)

_Should_ be considering adding a similar "What are the key points?"to other tutorials?_

**Comment by yatil** [comment]
> Should we be considering adding a similar "What are the key points?"to other tutorials?

I think we could look into that, I think having an almost checklist-like view of what needs to be done gives a great overview (similar to the alt decision tree).

**Comment by shwetank** [comment]
"What makes an accessible carousel?" works.

One more suggestion from my side - "Key features of an accessible carousal". or "Main characteristics of an accessible carousal" or something along that lines.

**Comment by kakinney** [comment]
I like @shwetank comment - What makes an accessible carousel?  I think that is a good opening question that each point on that list answers.

**Comment by yatil** [comment]
Thanks all for your input. I think we have candidates here:

1. What makes an accessible carousel?
2. What makes carousels accessible?
3. What are the key points? (Keep as is.)

**Comment by dboudreau** [comment]
How about "Key points for an accessible carousel"?

**Comment by yatil** [comment]
Group resolution in the Meeting of Feb 3: “What makes an accessible carousel?” (will add link)
