### ISSUE TITLE
Deadlink "landmarks" on page WAI/tutorials/page-structure/in-page-navigation

### ISSUE THREAD

**Issue by MarcusMorba** [w3c/wai-tutorials#414]
There´s a dead link "landmarks" (https://www.w3.org/WAI/tutorials/page-structure/in-page-navigation/landmarks.html) on page https://www.w3.org/WAI/tutorials/page-structure/in-page-navigation

Skip links
Skip links are historically needed to jump to different sections on the page. They were used before **landmarks** were implemented in browsers and assistive technologies and can still be useful in some situations.

**Comment by yatil** [comment]
Thanks for reporting the error, we have moved around the page and changed the links in the current editor’s draft which we hope to publish soon!
