### ISSUE TITLE
Label guidance

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#416]
Investigate if we need to change the guidance for implicit labels, see those tests:

* https://make.wordpress.org/accessibility/2017/01/16/testing-form-functionality-with-different-assistive-technology/
* wpaccessibility/test-forms#3

Thanks @rianrietveld!

**Comment by StommePoes** [comment]
There's another issue somewhere where @goestu brough exactly this up, I think for WCAG 2.1, but I can never find comments on GitHub, not even my own :(
