### ISSUE TITLE
[Navigation] disagree with current approach

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-tutorials#419]
The current approach has been discussed at the [November face-to-face](https://www.w3.org/WAI/EO/wiki/EOWG_F2F_November_2016/Tutorial_Discussion#Meeting_Outcomes) and on the [December 16th call](https://www.w3.org/2016/12/16-eo-minutes.html#item04). Yet as presented today, I feel that the Navigation tutorial seems unfocused and messy. I suggest changing this tutorial from "Navigation" to focus on "Menus" only - the rest can mostly fit into the "Page Structure" tutorial fairly well. Specifically:

1. **Move the "Anchors" section into the "Page Structure" tutorial**: Currently this section consists of two paragraphs - one explaining how URLs work, which I think should be dropped or reduced to one sentence, and another that basically says "add anchors so that people can bookmark and skip to them". I think this can be easily added somewhere to the "Page Structure" tutorial, such as in the "Headings", "Page Regions", and/or "Tips and Tricks" sections.
2. **Move "Skip Links" section into the "Page Structure tutorial**: Currently this section describes adding a list-type widget/component to pages, to help people skip to the relevant sections of a page. Again, this seems to fit well within the "Page Structure" tutorial, either as a new section or somewhere else in there.
3. **Move "Table of Content" section into the "Page Structure tutorial**: Again, also this seems to me to  be a page widget/component that can be easily fitted into the "Page Structure" tutorial, for example in a "Tips and Tricks" section there.
4. **Describe "Breadcrumbs" as a type of "Menu"**: This section can be kept in the new "Menus" tutorial. It follows the current approach of "structure - styling - content" quite well.
5. **Move "Sitemap" section to a "Tips and Tricks" section**: Currently this is a very short section and can fit easily in a "Tips and Tricks" section of the tutorial. Actually I don't even think this is a high-priority issue and we could even drop this for now, if it doesn't fit any of the tutorials.
6. **Keep "Search" as currently is in the "Page Structure" tutorial**. We already have a "Search" section in the "Page Structure" tutorial, and it would be good to avoid repetition, The suggested focus on "Menus" would help streamline the two tutorials and reduce repetition.

Side note: This comment is on the overall approach and not on the wording. I think the wording can be tightened up and made clearer. Also, I offered to Eric making pull requests with these suggestions but he wanted to check with the group first.

**Comment by yatil** [comment]
I do not agree that “the rest can mostly fit into the "Page Structure" tutorial fairly well”.

1. Anchors do not structure the page. They can be added to every element. They however work as a navigation mechanism.

2. Same goes for skip links. You don’t structure with skip links but you can navigate a structure with skip links.

3. Same as above.

4. Breadcrumbs are an alternative way to move through the site structure, which I think is navigation. I think we can have it on a separate page of a Menu tutorial, but on the other hand they fit well in the multiple ways.

5. I don’t like Tips and Tricks pages for important information. There is a WCAG SC that is called multiple ways, and I want to enforce that in the tutorial. I find it important. Our statistics also show that T&T pages are accessed significantly less than other pages (In tables 1/3rd of clicks than the next content page.)

6. I planned to remove Search from the page structure tutorial (I talked with @slhenry about that yesterday, basically as the page fits well in other pages or the proposed content is too specific.) Also I think search is more a navigation aid than a way to structure a page.

Happy to keep the discussion going.

**Comment by nitedog** [comment]
My continued concern is that we have a tutorial in a tutorial - the broad aspect of "navigation" with a fairly specific aspect of "menus". I think both are getting lost within this intermixing.

Could a different approach be to separate out a "menus" and "navigation" tutorial?


On points 1-3, I disagree with your assertion that these components are not part of the page structure but navigation. Same argument could be applied to "Headings" and "Labeling Regions" of the page structure tutorial - also these serve navigation under the same token.

Point 4 can go either way, it seems.

I agree with you that points 5-6

**Comment by yatil** [comment]
On 1-3, how does a table of contents structure the page? Headings are a result of the content. ToCs are a result of making the content navigable. If I don’t use assistive technologies, headings don’t provide navigation (but orientation).

Good to see that we get some common ground here. I might be convinced to pull out In-Page navigation and multiple ways and have a menus and a navigation tutorial (but I found that confusing when I tried it in December, and there was also some overlap). 

As the concepts are not as clear cut, and wording is used differently (I _think_ menus are often called “navigations” in Germany, for example, and menus is more like application menus.), I think the current structure is best suited to have readers find what they are looking for quickly without ambiguous categories.

**Comment by nitedog** [comment]
Glad we are finding common grounds too.

I think also the "Search" aspect could fit well into the new "Navigation" tutorial. Maybe other points too, like "Information Architecture" but not sure. We'd need to think more about that tutorial.

I agree that the word "navigation" is frequently used a short-hand for "main navigation bar/menu", which can be confused with the word "navigation" used as a verb/adjective. But I expect that the "Navigation" tutorial will cross-link to the "Menus" tutorial for specifics on navigation bars/menus.
