### ISSUE TITLE
[Navigation]-[Menu Styling]-information on All caps

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-tutorials#420]
People with Dyslexia and other reading disabilities find Capitalised words or long sentences hard to read.
As we recommend avoid line breaks etc, I think "Avoid using ALL CAPITAL letters" in menus should also be a recommendation as this was a common styling practice at some point.
I find this in lot of retrofitting works.

**Comment by yatil** [comment]
That’s a good point, I’ll see if we can add it easily. (There is no corresponding WCAG SC, so we need to word it carefully.)

**Comment by yatil** [comment]
@nitedog volunteered to look at that page, so I guess he’ll take a look a that. :-)
