### ISSUE TITLE
Concepts page - Wording in opening paragraph 

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#441]
[High][for editors discretion]
In the [opening paragraph](https://w3c.github.io/wai-tutorials/page-structure/) it states:
> It provides information to assistive technology which allows users to use them more efficiently.

What does the word "them" stand for? Is it, use the AT more efficiently, or use the web page more efficiently?

This needs clarification.

**Comment by yatil** [comment]
I’ll adopt @sharronrush’s rewording from #375, which is much clearer.
