### ISSUE TITLE
Labeling Regions - Too many commas

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#444]
[medium][editors discretion]

There are too many commas in the opening paragraph on the [Labeling Regions page](https://w3c.github.io/wai-tutorials/page-structure/labels/
). Possible reword for consideration below. Feel free to tweak or shorten.

Current wording:
> Most regions need to be labeled, especially if there are multiple regions of the same type, for example multiple navigation options, on a page. WAI-ARIA provides simple mechanisms to label a region, enabling users to easily navigate around the page.

Suggested working:
> Most regions on a page need to be labeled, This is especially important when there are multiple regions of the same type on one page, such as multiple navigation options. WAI-ARIA provides simple mechanisms to label a region, enabling users to easily navigate around the page.

**Comment by yatil** [comment]
Removed 50% of the commas as per your suggestion :-)

4bc7d3e8c466b04e47e9ee8195c119f1ef96537e
