### ISSUE TITLE
Labeling Regions - non-congruent

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#445]
[medium] - explanation in thread from editor may be sufficient to close issue

In the [Approach 1: Using aria-label](https://w3c.github.io/wai-tutorials/page-structure/labels/#using-aria-label) section, the first sentence talks about using the attribute to label "the carousel." The code snippet talks about labeling the Main Navigation. 

This seems out of sync to me. Should the first sentence say to use the attribute to label "the main navigation" so it matches the code snippet more closely?

**Comment by yatil** [comment]
This was a copy and paste error from the carousel tutorial, where the content originated. Was fixed in 9a9d619114a20b46086be8f4f4f028c0427beac2.
