### ISSUE TITLE
Labeling Regions - Missing "Next" link

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#446]
[High]

At the [bottom of the Labeling Regions page](https://w3c.github.io/wai-tutorials/page-structure/labels/#related), the "Next --> Headings" link to go to the next tutorial page is missing.

**Comment by yatil** [comment]
Thanks for spotting this. It has been fixed in 920519fac71773b027b3c3e9b167b2064ca51acb.
