### ISSUE TITLE
Headings - Reword opening paragraph

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#447]
[High][editors discretion]

The Headings page [current opening paragraph](https://w3c.github.io/wai-tutorials/page-structure/headings/) reads a little clunky with not much sense. Rewording suggestion below. Tweak as needed.

Current wording:
> Use headings to communicate organization of the content on the page. They allow web browsers, plug-ins, and assistive technologies provide mechanisms for users to navigate through web pages.

Suggested wording:
> Use headings to programmatically communicate the organization of the content on the page. Headings provide web browsers, plug-ins, and assistive technology mechanisms for users to navigate through web pages.

**Comment by yatil** [comment]
Fixed in 7c52a9bf1f6a28e4fb993427775ef7469e8e7df2.

I removed the word “programatically” from your suggestion, as headings do more than that (also it is a “big” word and it is clear from the second sentence, I think. :-))
