### ISSUE TITLE
Headings - Provide visual example for clarity

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#448]
[medium/high] [okay with group decision]

In the [Heading Levels section](https://w3c.github.io/wai-tutorials/page-structure/headings/#heading-levels
), there is a good explanation of the proper ordering of heading tags. However, for those that are new to this concept, it would be simplified with a nice graphic showing an example of content and the heading structure used in the content.

For example (**please find a better example and use less space to show it**):
<h1>Components of an Automobile (h1)
<h2>Exterior (h2)
<h2>Interior (h2)
<h3>Seats (h3)
<h3>Dash (h3)
<h4>Speedometer (h4)
<h4>Audio controls (h4)
<h2>Safety Equipment (h2)
<h3>Antilock brakes (h3)
<h3>Airbags (h3)

**Comment by bakkenb** [comment]
After reading further down the page, the examples in [Approach 2](https://w3c.github.io/wai-tutorials/page-structure/headings/#organize-page-regions) could be used as the content for this visual.

**Comment by yatil** [comment]
Hm. The page is relatively short, I wonder if it is really worth duplicating content. Happy to discuss that in the group.

**Comment by yatil** [comment]
Hi @bakkenb and @nitedog,

can you review https://w3c.github.io/wai-tutorials/page-structure/headings/? I hope it goes into the right direction…

**Comment by yatil** [comment]
Some of the wording around the heading ranks was lifted from HTML5.1: https://www.w3.org/TR/html51/sections.html#headings-and-sections

**Comment by bakkenb** [comment]
Thanks Eric. This is a good start. There are a couple of things that I think need some change. 

1. Would like to see the example come inline, *after* the paragraph that starts out "Do not skip ranks..." Could lead with a image title of "For Example"
2. Would like to see the example font be a little smaller. Maybe same font size as the page main content font.
3. Would like to see the example of jumping back to an (h2) right after an (h4)... like it is described in the preceding paragraph.

Great start. Hope this helps.

**Comment by yatil** [comment]
Good points, @bakkenb, I’ll adjust!

**Comment by yatil** [comment]
I made the changes. Re: 2 – I think I thought about headings and used a big font. Which is not needed for the example to work.

I made all other changes.

**Comment by bakkenb** [comment]
Looks Great. Much improved. Location is good. Maybe above the graphic put the title "For Example" or "Example".  [editor's discretion]

Very good. Thank you.
