### ISSUE TITLE
Headings - Approach 1 Sentence needs editing

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#449]
[high] [editor needs to edit]

The first sentence in the [Approach 1: Organize main content](https://w3c.github.io/wai-tutorials/page-structure/headings/#organize-main-content) section is not correctly written. I am not sure exactly what is trying to be said so I am not offering a rewording. Please reword.

Current Wording:
> Use headings are used to only organize the main content of the web page:

**Comment by yatil** [comment]
Fixed with #463.
