### ISSUE TITLE
Content Structure - </li> tag out of place

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#452]
[medium]

In the [Nested List section](https://w3c.github.io/wai-tutorials/page-structure/content/#nested-lists) there is an example and a code snippet. In the code snippet, there is an end list item tag following the "cut vegetables in small cubes" text that is out of place. It is on the next line. Reformat so that it is on the same line following the text.

I know code wise it does not matter, but it doesn't look good.

**Comment by yatil** [comment]
@bakkenb This looks fine to me:

![](https://cloud.githubusercontent.com/assets/58862/24234715/092c2702-0f9a-11e7-96e2-101f28cf3dfa.png)

Is this what you’re seeing as well? (I tried different resolutions and all were OK, too.)

**Comment by bakkenb** [comment]
No, this is what I see (on Windows 7 in Chrome)

![image](https://cloud.githubusercontent.com/assets/11727417/24268678/904ed4cc-0fdc-11e7-8bd5-2102ad7942ac.png)

**Comment by yatil** [comment]
This is weird, I tested in Chrome (on Mac). I’ll try to have another look!

**Comment by yatil** [comment]
I found the error and corrected it.

**Comment by bakkenb** [comment]
That fixed it. Thanks!
