### ISSUE TITLE
Code for last section - Page Regions in HTML 4 Using WAI-ARIA - was confusing

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-tutorials#456]
~~~html
<header role="banner">…</header>
<main role="main">…</main>
<nav role="navigation">…</main>
<footer role="contentinfo">…</footer>
~~~

[what about the aria labels that were used in the previous section? Should they also be used here?]

**Comment by yatil** [comment]
I’ve clarified that – among other things – in 4561e2c3d81cc75172bb4a6ccd68e0cbaed6d895.
