### ISSUE TITLE
If image contains text that isn't present elswhere then alt should be the info conveyed

### ISSUE THREAD

**Issue by accessiblewebuk** [w3c/wai-tutorials#458]
It says "Does the image contain text?" then if yes "… and the text in the image is not present otherwise.
Use the alt attribute to include the text of the image. See Images of Text." 

This is often OK but not in the case where a literal representation of the text doesn't convey the information As an example an image of an asterisk might be used by form field to indicate "required", in which case the alt should be "required", not the literal text "asterisk". The flowchart isn't clear on this point.

**Comment by yatil** [comment]
Thanks, @accessiblewebuk, good feedback. (It is on the detail pages, but it will be good to highlight it in the alt decision tree.)
