### ISSUE TITLE
[page structure] concepts

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-tutorials#460]
Minor editorial comments:

1. Both sections start with "A good page structure..." - some variance would be nicer.
2. "in particular for those with cognitive and learning disabilities" - please add an item to the bullet list below rather than inline (also avoid "those" as it sounds a bit like "them and us").
3. Same for "people with visual impairments" - this is what the list below is for.
4. Same for search engines.
5. s/predictions/indexing ?

**Comment by yatil** [comment]
See commit 621c2dbe59d064c7b8203654062db474494d0225.

1. D’oh!
2. Double D’oh!
3. Triple D’oh!

I have them all fixed.

4. I wanted to have some difference between users and “just” search engine benefits. I decided to add the Sentence to the bullet list but not bolden anything (as I have user groups bold in the other list items and this is none).

5. Reworded!
