### ISSUE TITLE
[page structure] Lebeling Regions

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-tutorials#461]
Minor editorial suggestions:

1. Sections should also organized using headings -> Sections should also be organized using headings
2. Use the WAI-ARIA aria-label attribute to label the carousel -> Use the WAI-ARIA aria-label attribute to label the region
3. This approach can be used if the label is not supposed to be visually on the page -> This approach can be used if the label is not supposed to appear visually on the page
4. Missing next link (arrow to the next page in the tutorial)

**Comment by yatil** [comment]
Great edits! See 9a9d619114a20b46086be8f4f4f028c0427beac2.

**Comment by yatil** [comment]
4. Thanks for spotting this. It has been fixed in 920519fac71773b027b3c3e9b167b2064ca51acb.
