### ISSUE TITLE
[page structure] Page Regions

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-tutorials#462]
Minor editorial suggestions:

1. Mark up different regions of web pages and web applications -> Mark up different regions of web pages and applications
2. The HTML4 examples at the end of the page are really tiny and too difficult to read (for me at least)

**Comment by yatil** [comment]
1. Done (4a3ec76d0f5877d2201cdaf17d67065c4bf3f7bf).
2. Duplication from #443 and fixed.
