### ISSUE TITLE
[page structure] Headings

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-tutorials#463]
Minor editorial suggestions:

1. In fixed sections of the page, for example in the footer -> In fixed sections of the page, for example in the side bar (or menu?) ... footer just seems odd to me
2. Are these really approaches? To me "approaches" sounds mutually exclusive. I think make these just normal page sections "Organizing passages of text" and "Organizing page regions" or such.
3. Use headings are used to only organize the main content of the web page -> Use headings to organize text passages in a web page (these do not have to be the main content, but could also be sections).
4. In both examples (which could actually be approaches rather than examples), change "navigation" to "navigation menu" to make it clearer.
5. No back link (arrow to the previous page in the tutorial).

**Comment by yatil** [comment]
1. The footer was used as an example as many websites have link lists with headers in the footer. I agree that sidebars are a better example.
2. I think they are approaches – Either you use headings _only_ for the content or you use headings for page structure _and_ the content. – However I don’t think the approaches wording is needed here.
3. OK.
4. OK.
5. Already fixed.

Fixes here: 7f4892c8ca6d1a0a2713f6b0ca21bec7f15c8d0b.
