### ISSUE TITLE
[aria-concepts-with-sliders] Why Sliders?

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-tutorials#469]
Wondering why we are doing the tutorial on Aria concepts with sliders?  Aren't there more basic options like check boxes or radio buttons (totally boring stuff, I know) that people may find more universally useful?

**Comment by sharronrush** [comment]
This is a good point and gets to the tendency we have to silo certain topics and treat them as if they are somehow separate from the whole practice of accessibility. Mobile for example. We have several references to ARIA within the existing tutorials which is the way for this to be most effective in my opinion. If the purpose is "How to use the ARIA Authoring Guide" that may be more useful. If that is the point, then it seems we may not want to focus on only one component but use several examples of how you might reference the Guide as you build your widget.

**Comment by kakinney** [comment]
@brewerj - this was my comment.

**Comment by nrhsinclair** [comment]
I agree with that statement and that's where I was hung up. A more basic example would be a good starting point in an introduction.

**Comment by mcking65** [comment]
I think the goals/purpose Judy and I discussed will become more clear as we hammer a little more shape into the tutorial.

Basically, there are a few things everyone should understand about ARIA before you use it at all. They are things that must be stated in several ways in several places, and can't be repeated often enough.

These are things we want people to understand before they start using what is in the APG. They will be restated in a similar way in the APG intro. And, I plan to have the APG intro point people to this tutorial as well. 

My plan is to use a real life example that is super simple to get these points across. We will talk primarily in code; the goal is to reach people who learn that way.

I was originally thinking of using checkbox to teach these concepts, but after discussion with some engineers here at Facebook about what we see in real life, button will serve the purpose better. In everyday engineering, there are more reasons not to use an html button than not to use an html checkbox. And, we see that reflected in our code base as well as in publicly available code.

**Comment by yatil** [comment]
> In everyday engineering, there are more reasons not to use an html button

Playing devil’s advocate here :-) I can’t think of one reason not to use an HTML `<button>` element :-) Happy to learn in what situations they are not working.

**Comment by mcking65** [comment]
Styling limitations, state/property limitations.

**Comment by yatil** [comment]
This issue was moved to w3c/wai-aria-intro#11
