### ISSUE TITLE
Purpose, goal

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-tutorials#471]
How did we determine this goal, is there some research about gaps in the field that need to be addressed? I am concerned that we are trying to solve problems that we don't fully understand and I support collecting more data.  I strongly agree that our current treatment of mobile is way off the mark and that there is much confusion about ARIA implementations. I think these are excellent topics to address and expect that WCAG 2.1 will be clarifying.  In the meantime however, I just want to be sure that our approach is actually going to be helpful rather than adding to the muddy waters. 

Ongoing community surveys rather than anecdotal and internal conversations would seem to illuminate real needs from the field. If our approach is more along the lines of "How to use...[ARIA authoring Guide, WCAG for mobile, UI Components List, etc] I would have more confidence that we are creating resources that people may actually find useful.

**Comment by brewerj** [comment]
Reply as of 20170330 (may evolve as comments & input evolves): 
How determine goals for the 4 proposed tutorials: in some cases based on ongoing and frequent requests for clarifications, for instance on application of WAI guidelines to mobile, and positive responses to suggestions of a tutorial-like overview; in other cases, from discussions with ARIA developers; in other cases, from tutorials wishlist and other feedback. 
Is there research about gaps in the field: Not formal research (perhaps good approach to take in new charter). If there are existing examples of such research that EOWG has done already, that would be helpful to see.
I agree that we need to refine our understanding of the purposes & reflect that in the approaches.
For mobile overview and aria conceptual intro, might seem particularly relevant to explore a tutorial/guide approach -- however, I'm concerned that the ARIA Authoring Practices guide is monumental, whereas the intent of the mobile overview piece would be mainly to point at other things, not to have a series of fully developed mini-topics within it.
I think that a mock-up or two would make this more understandable. Will work on that.
