### ISSUE TITLE
Printing issue

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-tutorials#472]
I was trying to print part of the Images tutorial for a colleague and got pages that looked like this.  
Tried it in Chrome, Firefox and Safari.  
<img width="471" alt="wai images tutorial printing" src="https://cloud.githubusercontent.com/assets/23261002/24427166/02adf44a-13d8-11e7-982b-c01648296802.png">

**Comment by yatil** [comment]
We do that to save trees ;-) 

It should be fixed in the editors draft: https://w3c.github.io/wai-tutorials/

**Comment by yatil** [comment]
I just re-tested it from Safari 10.1, and indeed the editor’s draft is printable, see [PDF](https://github.com/w3c/wai-tutorials/files/878865/PREVIEW.Images.Concepts.Images.WAI.Web.Accessibility.Tutorials.pdf).

**Comment by yatil** [comment]
BTW that was fixed in #306 & #307.
