### ISSUE TITLE
[ARIA w/ Sliders] Scope

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#476]
I generally don’t think that tutorials should be broad overviews, but more focused. Also I am concerned with how this tutorial is framed. We want to provide technique-inclusive tutorials, not siloed of tutorials. Maybe here it is also appropriate to see if parts of the draft can be repurposed for the ARIA Overview pages.

We already have a lot of ARIA guidance in the current tutorials.

**Comment by bakkenb** [comment]
I am in favor of having this be more of a guide than a tutorial. I like the concept of a guide or overview understanding resource of ARIA, what it is for, examples, when to use, when to not abuse, etc. A lot of the ideas in this outline are good. This topic just doesn't lend itself to a succinct tutorial. I understand that the tutorial would/could focus on one examlpe, like the slider and then more understanding content around ARIA, but that doesn't seem to match our current tutorial structure. 

On another note, I do think that the tutorial "area" is a place to generate views/interest in this topic of understanding ARIA and knowing where to find the ARIA Authoring Practices document. I would be interested in turning this into a more comprehensive guide, many of the outlined concepts, an example or two of components with ARIA code, and links to supporting documentation and the Authoring Practices. Then find a way to call attention to it in the tutorials or some sort of a developer landing area.

**Comment by bakkenb** [comment]
An idea for consideration...

In regards to the updated [Overview for "ARIA Introduction for Developers,"](https://www.w3.org/WAI/EO/wiki/Tutorial_Mockup_ARIA_Concepts) what about adding another example on the Draft Page 3 "ARIA Advanced Concepts". Would be good to have an advanced example to drive home some advanced concepts. I know that a couple of people on the call thought it would be good to have more than one example.

**Comment by nrhsinclair** [comment]
Perhaps providing an example focused on something many developers commonly spend a good deal of time working on, like navigation is a good introduction where the slider example seems less common. (i think that is why I feel as though two examples would be helpful, or starting with an example of something more common.)

**Comment by yatil** [comment]
This issue was moved to w3c/wai-aria-intro#10
