### ISSUE TITLE
[Datepickers] Scope/AUIC

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#477]
With the delay of the Accessible UI Components List, it might be better to not tie it in that much. I also think that an intro tutorial for the UI Components list is better served as support material there. I’d be interested in a Datepicker tutorial (but heard we don’t want to double the efforts that have been done in the practices guide).

Other worthwhile tutorials that we could do: Shopping cart. Hamburger Menus. Modal dialogs. Infographics.

**Comment by yatil** [comment]
After reviewing what is in APG 1.0 (date pickers are not in 1.1 yet), I think we might want to consider the following proposal:

https://www.w3.org/WAI/EO/wiki/User:Eeggert/Tutorials/DatePickerAlt

**Comment by brewerj** [comment]
Ideally if the UI Components list were ready I think it could help some audiences that might not have used a components library before to bridge the space from the tutorials to the UICL. Or, maybe the call-out boxes for additional resources in the tutorials would be sufficient to get them there without something directly discussing the UICL. But I understand that the timing is unlikely to work on that before this tutorial would be done. The tutorial (or tutorial/guide) could be updated later.

If this tutorial were only focused on ARIA date-pickers, it would be redundant with upcoming ARIA APG content, and there's no intent to be redundant.

But the approach you're suggesting of showing (or linking to) a range of non-ARIA as well as ARIA examples might be interesting to explore.

How robust a set of non-ARIA techniques do you think could be shown?

**Comment by yatil** [comment]
Adrian Roselli on Date Pickers: http://adrianroselli.com/2019/07/maybe-you-dont-need-a-date-picker.html
