### ISSUE TITLE
[Accessible Media Tutorial] scope broader than captions

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#478]
I think this tutorial could be easily changed to include other video-related content and become a proper video component tutorial. Proposal:

https://www.w3.org/WAI/EO/wiki/User:Eeggert/Tutorials/CaptionsAlt

**Comment by brewerj** [comment]
Yes if you note the original outline, transcripts and described video are also covered, but could benefit more balanced treatment, and renaming it may help.

**Comment by bakkenb** [comment]
Would like to consider (if not too overwhelming) this tutorial referencing and covering all of [Guideline 1.2 Time-based Media](https://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv.html) (SC 1.2.1 - 1.2.9). This would give a much more comprehensive overview to content creators and developers of what should be implemented for all time-based media. What types of accommodations and when should they be implemented.

**Comment by yatil** [comment]
+1 @bakkenb (As long as we manage to call the tutorial something other than “Time-based Media” 😉 “Audio and Video” would work, or Audio, Video and Movement/Animation.)

**Comment by nrhsinclair** [comment]
This definition is a little unclear to me:
Captions: A visual representation of the program-audio track, fully synchronized with the audio. 

Suggest changing "visual representation" to "text versions" 
Captions: Text versions of the program dialogue and narration, or other spoken words, fully synchronized with the program audio and displayed within the media player. Captions also include text identifying music and sound effects. (That suggestion may be too long, but main point is to change visual representation to "text version". Last sentence helps differentiate captions from subtitles.)

**Comment by nrhsinclair** [comment]
Transcript: A unsynchronized visual representation of the audio track, containing narration or dialog plus non-speech information such as speaker-identification cues.

suggest changing "visual representation" to "text file"

Also include short sentence on Interactive transcript since they are becoming more common.

**Comment by bakkenb** [comment]
I have added both of @nrhsinclair's comments above as new separate issues. #503 & #504

**Comment by brewerj** [comment]
This comment has been addressed (or set as pending) in the forked comments that Eric created. Closing now...
