### ISSUE TITLE
[Mobile Overview] Suggest mobile authoring guide

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-tutorials#479]
Because mobile is such a broad topic I wonder if a "tutorial" will address the need in a truly useful way. The way we currently address mobile reinforces the misconception that mobile design is separate from WCAG and that approach contributes to greater confusion. Maybe creating a mobile authoring guide that ties to WCAG instead of expecting one tutorial to do all this work. Such a resource could mimic the ARIA Authoring Guide and provide consistency in the approach.

**Comment by bakkenb** [comment]
I also agree with Sharron's perspective as lately we have been trying to show that mobile development considerations are all throughout accessible design and responsive design. I do like the idea of a guide or landing page that explains this and gets developers into some of the resources that address this responsive design approach that includes for mobile.

**Comment by haltersweb** [comment]
Maybe we can instead say "Mobile Primer" instead of "Mobile Tutorial"

**Comment by yatil** [comment]
This issue was moved to w3c/wai-mobile-intro#28
