### ISSUE TITLE
[Accessible Media Tutorial] Include accessible player information

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#482]
I think it would be important to include a section or page on accessible players to compliment the captions tutorial. Defining all of the different functionality of accessible players. Identifying things that are necessary for a player to do, as well as nice to haves and overkill (clutter) functionality. Maybe we could even point to a few of the free players that can be used.

**Comment by yatil** [comment]
I think it’s essential to show an accessible implementation of a video player, see my comments in #478.

**Comment by brewerj** [comment]
Added a page describing generic considerations about players, avoiding showing specific products per previous EOWG recommendations. 
https://w3c.github.io/wai-tutorials/accessible-media/playing/
