### ISSUE TITLE
[page structure] concepts

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-tutorials#484]
This has come a long way - well done!
Priority: medium (I thing the modifiers overstate the reality)
Minor rewrite of first couple of sentences, just removed two words ('quickly' and 'more')  because they overstate:

Page structure is a useful way for all users to understand how content is related. For users of assistive technology, well-structured content allows efficient navigation and processing. 

No further changes

**Comment by yatil** [comment]
@nitedog made a strong case that we might not even need the first sentence, and I think he’s right. So it got removed: https://github.com/w3c/wai-tutorials/pull/483#pullrequestreview-31904637 :-)
