### ISSUE TITLE
[page structure] page regions

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-tutorials#485]
Priority: editor's discretion
I like the side bars but suggest to find alternative for repetition of "is available." Seems too passive and unspecific.  what about "view example of ..." or "explore..." or something more encouraging?

**Comment by bakkenb** [comment]
What about "View a complete example for all regions combined."

**Comment by yatil** [comment]
I made some changes, see 3a66db9985d13e21503291911669d39657be9c4d.
