### ISSUE TITLE
[page-structure] headings

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-tutorials#486]
1.  Clumsy, ambiguous phrase: 'to provide navigation for the page to users.'
Suggest: 'to provide page navigation.'
Priority: Must be addressed

2. Are we comfortable with such a strong assertion about skipping heading levels since that is not an actual WCAG requirement? 
Priority: editor's discretion

**Comment by yatil** [comment]
Happy to implement 1) :-)

@nitedog Any reactions to 2) – I think @sharronrush is right, so I propose the following change:

> ~Do not skip ranks~ ++Avoid skipping ranks++ when creating subsections:

**Comment by nitedog** [comment]
Yes, I agree with @sharronrush. Maybe even softer:

> "Skipping heading levels can be confusing and should be avoided where possible:"

A bit more wordy but (1) explains the rationale and (2) provides an escape clause.

**Comment by nitedog** [comment]
Side comment - there are also other questions, like "is it allowed to have more than one H1". These are only implicitly addressed on this page, and it may be good to be more specific (as you do with skipping levels).

**Comment by bakkenb** [comment]
I also agree with part 2 of this thread. The way it is worded now is not correct if you think if it in absolute terms. 
+1 to @nitedog : 

> "Skipping heading levels can be confusing and should be avoided where possible:"

**Comment by iamjolly** [comment]
+1 to @sharronrush's part 1.

+1 to @nitedog's suggestion for wording of skipping heading levels.

**Comment by yatil** [comment]
I’ve implemented part 1 and 2.

@nitedog – re: 

> Side comment - there are also other questions, like "is it allowed to have more than one H1". These are only implicitly addressed on this page, and it may be good to be more specific (as you do with skipping levels).

Any wording suggestions? I can only think of a general sentences like “Depending on the page content structure, it can be suitable to use one or multiple headings of rank 1.” or “If a page has multiple main sections, it can be appropriate to use multiple headings of rank 1.”

(As this was only a side comment, I don’t think this blocks publication, right @nitedog?)

**Comment by nitedog** [comment]
No, this is not a show-stopper. Totally editors' discretion. I also don't have a specific suggestion. We ran into a similar problem with the images tutorial, and ended up with a "tips and tricks" section. On the "styling" page of the carousels tutorial you also seem to have a set of generic factoids but approached differently than "tips and tricks". Any of these approaches could work, but I would suggest to do this as directly as possible, like FAQ style. Hope these thoughts provide some inspiration...

**Comment by yatil** [comment]
Thanks, @nitedog! I decided to table it for now, but I’ll capture that aspect in another issue and hope to address it soon after the initial publication! :-)
