### ISSUE TITLE
[page structure] Content structure

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-tutorials#487]
Priority: Editor's discretion
Clunky sentence: Mark-up website content semantically, so that the website is extensible, the content reusable and also conveys more meaning to assistive technologies.

Suggest: Mark-up website content semantically, so that the website is extensible. Valid semantics create content that is reusable and more meaningful to assistive technologies.

**Comment by bakkenb** [comment]
+1

**Comment by yatil** [comment]
Done! :-)
