### ISSUE TITLE
[ED][Page Structure Concepts] Why is this important (edit)

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-tutorials#488]
For editor's discretion:

Under the heading "Why is this important?" the sentence that reads:

> Well-structured pages are essential for many web users, including:

...can be removed. The bullets below it do not complete the sentence but are complete sentences of their own that answer the question in the heading (Why is this important?).

**Comment by bakkenb** [comment]
I understand what @iamjolly is saying here. Would it work to replace it with...

"Well-structured pages are essential for many web users, for example..."

**Comment by yatil** [comment]
As @nitedog’s proposal in #483 put “Well-structured content…” as the first sentence of the page, we have a duplication here. I think @iamjolly is right that the sentence can be outright removed, this “why is this important” section does not need an intro sentence.

**Comment by yatil** [comment]
… but then, we want to make clear that the list is not exhaustive. :-) 

I have changed the sentence to:

> Pages with well-structured content are essential for many web users, for example:
