### ISSUE TITLE
[!!][Page Structure – Content Structure]

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#490]
[Not sure if this "Must" be changed or if it isn't an issue at all...]

This pertains to the "Quotes" section. 

I am wondering if we need to add a simple sentence in the intro paragraph as to why it is important to use the following tags:
- (blockquote)
- (cite)
- (q)...(/q)

If I was a developer, which I am not, I would just italicize the (cite) text, as well as just type the " " symbols around the quoted text. I wouldn't know why it is important to use those particular tags instead. 

Actually, I don't know why those tags should be used instead. I am assuming that it is because assistive technology will interpret it more appropriately to the user. If I don't know the reason, maybe others will not either.?.?

**Comment by iamjolly** [comment]
I like @bakkenb's suggestion to:

> add a simple sentence in the intro paragraph as to why it is important to use the following tags:
> * (blockquote)
> * (cite)
> * (q)...(/q)

One thought I'm having in terms of communicating the importance of using the semantic markup is that, as a developer, you're ensuring the _robustness_ of the content for varied, possible future use. One example is allowing search engines to have a reliable way of cataloguing quoted/cited data. Don't ask me how to turn that thinking into a simple sentence right now, though. :)

**Comment by yatil** [comment]
What about thinking simple and use:

> Assistive technologies can convey to users where a quote starts and ends, which can avoid misunderstandings.

I thought about a good example for that, but I can’t come up with one.

**Comment by bakkenb** [comment]
This works for me. I just think it needed a quick explanation of why it is helpful to use the right markup.
