### ISSUE TITLE
[ED][Menus Concepts] Application menus (minor edits)

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-tutorials#493]
## Issue 1:
I don't understand the use of the word "particular" in the following sentence for application menus:

> *Application Menus:* Add particular markup and keyboard behavior to resemble desktop application menus.

Perhaps we can remove "particular" altogether or replace it with something like "specific."

## Issue 2:
Misplaced comma in the following sentence:

> Thus menus are critical parts of web pages and applications, and require particular attention during design and development.

should probably be:

> Thus, menus are critical parts of web pages and applications and require particular attention during design and development.

**Comment by yatil** [comment]
Issue 1 was addressed with #492.

On Issue 2:
@nitedog and I talked about that for some time, and we averaged in on “particular” to make sure that you have to use a certain markup, with both not feeling strongly. I can see “specific” and would go with it if there are no other hard feelings.

**Comment by nitedog** [comment]
I think you have your issue numbering mixed up ;-)

"specific" works for me. It was the word "special" that can of seemed unnecessarily mysterious.

**Comment by yatil** [comment]
Hahaha. Sorry, this free form sub-issue numbering (issue sub-numbering?) is not working for my German brain.

Anyhow, I’ll do “specific”!
