### ISSUE TITLE
[ED][Application Menu Example 

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#494]
On Window 7 using Chrome...

The menu example at the top of the page is in a container. When I click with mouse or tab and activate a menu using the keyboard the fly-out portion cannot be seen unless I go over and scroll down using the scroll bar that suddenly appears.
![image](https://cloud.githubusercontent.com/assets/11727417/24932954/7e3187ba-1ed9-11e7-86a4-10cc7c468edd.png)

Is there any way to make it so the container shows the fly-out part of the menu without scrolling?

**Comment by iamjolly** [comment]
I can confirm the same scroll bar issue on Windows 10 and Chrome (57 - latest).

**Comment by yatil** [comment]
I’ve fixed it! (Note: Bugs like this are not Editorial Discretion :-D)

**Comment by bakkenb** [comment]
Thanks for fixing. Didn't know if it was a bug, or if you intended it to scroll.  ;)

**Comment by bakkenb** [comment]
Oops, just checked it. It is still doing the same thing. The issue is on this page: <https://w3c.github.io/wai-tutorials/menus/application-menus-code/>
I have refreshed and cleared cache.

**Comment by yatil** [comment]
I have yet to publish the fix. :-)

**Comment by yatil** [comment]
Changes are now published. Man, you’re so fast so early! :-D

**Comment by bakkenb** [comment]
It works!!! Thanks Eric.
