### ISSUE TITLE
Notes icon/styling

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#498]
@nitedog from [the survey](https://www.w3.org/2002/09/wbs/35532/tutorials-review-april-2017/results):

> The Note looks like a warning and kind of scary to me. This is generic styling issue beyond the scope of this tutorial. Editors' discretion.

**Comment by yatil** [comment]
Would a different icon work for you? It is supposed to be an “information” i. Or is it the color? I wanted to distinguish it from the demo boxes… It would be easy to change to a gray color, for example.

That said, we change the design with the redesign anyway.

**Comment by nitedog** [comment]
It is the combination of red with the exclamation mark icon that makes it look like a warning rather than a friendly note. Can wait for the redesign in my point of view, just wanted to note the issue.

**Comment by yatil** [comment]
Thanks!
