### ISSUE TITLE
[Accessible Media Tutorial] Concepts Page

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#503]
Added by Norah Sinclair:

> This definition is a little unclear to me:
> Captions: A visual representation of the program-audio track, fully synchronized with the audio.
> 
> Suggest changing "visual representation" to "text versions"
> Captions: Text versions of the program dialogue and narration, or other spoken words, fully synchronized with the program audio and displayed within the media player. Captions also include text identifying music and sound effects. (That suggestion may be too long, but main point is to change visual representation to "text version". Last sentence helps differentiate captions from subtitles.)

**Comment by gfreedncam** [comment]
Done.
