### ISSUE TITLE
[Accessible Media Tutorial] Concepts Page

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#504]
Added by Norah Sinclair:

> Transcript: A unsynchronized visual representation of the audio track, containing narration or dialog plus non-speech information such as speaker-identification cues.
> 
> suggest changing "visual representation" to "text file"
> 
> Also include short sentence on Interactive transcript since they are becoming more common.

**Comment by kakinney** [comment]
Should also read:  Transcript: An unsynchronized...  not A
