### ISSUE TITLE
[Accessible Media Tutorial] Concepts Page - Minor edit

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#505]
[location] [Concepts page](https://www.w3.org/2017/04/xsmedia-tute/Overview.html) - Why is this important? section

[current wording] "Captions can be used by people who are hearing: for example, in noisy environments such as a bar or an airport lounge, or in any place where it would be inappropriate to turn up the volume."

[suggested wording] "Captions can be used by all people: for example, in noisy environments such as a bar or an airport lounge, or in any place where it would be inappropriate to turn up the volume."

**Comment by gfreedncam** [comment]
Done.

**Comment by bakkenb** [comment]
Sorry, Closed to soon. Others may see this before the update gets posted and re-open another issue on it. Can close again once the update is posted.

**Comment by brewerj** [comment]
That update has now been posted with a previous round, so, closing again now...
