### ISSUE TITLE
[Accessible Media Tutorial] Transcript Page 5

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#507]
In the opening sentence on the [Transcript Concepts and Examples - Page 5](https://www.w3.org/2017/04/xsmedia-tute/page5.html)

I would like to have the following statement reconsidered:
> A transcript is an unsynchronized textual representation of a program's audio track. They have a wide variety of uses:

Although typically unsynchronized, sometimes transcripts can be displayed as synchronized ([like in this example](https://www.w3.org/WAI/perspectives/keyboard.html), turn transcript on for demonstration).

Maybe we say "A transcript is a textual representation of a program's audio track. They have a wide variety of uses:"

**Comment by gfreedncam** [comment]
Done; conformed this definition to match the new one on overview.html.  Also added a link to https://www.w3.org/WAI/perspectives/keyboard.html as an example of an interactive transcript.
