### ISSUE TITLE
[Accessible Media Tutorial] - Audio descriptions Page 6

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#508]
[Location] Under "Description Basics" on the [Production options for audio descriptions](https://www.w3.org/2017/04/xsmedia-tute/page6.html) page.

Part of this section reads:

> Most described content today is presented with open descriptions, using one of two options:
> 
> - Two separate videos, one with open descriptions, and the other with no descriptions. Authors give users a link or some other method to choose one or the other.
> - A single video that contains two audio tracks, one with descriptions and one without. Authors give users a button or menu to toggle from one track to the other.

Isn't the second bullet here actually describing **closed** audio descriptions? Seems like the bullet should not be in this list describing **open** descriptions.

**Comment by gfreedncam** [comment]
Well, yes and no.  They are closed in the sense that you can choose to hear them, but really they are open because if you choose to watch the described video, you cannot turn off the descriptions.  (Actually, the only way to turn them off is to close the video and go watch the UNdescribed version, no?)  Make sense?

**Comment by bakkenb** [comment]
It does make sense. Thank you for the explanation Geoff.

Still a little confusing the way it is stated though. When I see the phrase "button or menu to toggle from one track to the other," I think that means "on the fly," switching to another audio track in the video. Which is different than if you toggle it off, and it will start from the beginning of the video using the other audio track without the audio description. I think toggle is the word that is the culprit here.

Interested what others think.

**Comment by gfreedncam** [comment]
Hi, Brent:

Good point, and I will clarify this.  I didn't see your note until I had sent out today's changes so I'll include this edit in the next round, probably early next week.

Thanks.
Geoff

**Comment by brewerj** [comment]
Brent, Geoff has addressed this is the latest set of files, to be available today. Closing now.
