### ISSUE TITLE
[Accessible Media Tutorial] Audio Descriptions - Page 6 - Extended

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#509]
Would like to add a small bit of information about Extended Audio Descriptions. Often times there are no pauses or breaks in the dialog/audio parts of a media file to include normal audio descriptions. In order to be accessible one must include [Extended Audio Descriptions](https://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-extended-ad.html). There is considerable video editing work involved if done after the fact. It is good for people to know about this so they can adjust in video production if they have the opportunity.

**Comment by gfreedncam** [comment]
Good idea-- I will add this during next week's revisions.  I believe I have an example or two that I can put on a server for demos.

**Comment by gfreedncam** [comment]
done-- added information about extended descriptions and a link to an example.
