### ISSUE TITLE
[Accessible Media Tutorial] - General comment on media production

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#510]
I believe it is worth mentioning the importance of quality synchronized media production in general as a precursor to working on captioning and audio describing content.

From my experience, before you even get to the stage of producing these accommodations, it is very important to have the highest quality media file possible going into the project. May a few words about this. Some examples could be:
- Speaking clear and crisp during recording
- Eliminated background noise and technical feedback
- Providing correct spelling of speaker names
- Quality microphone for recording original audio
- Quality video recording device and software to ensure best audio quality is rendered and saved
- etc.

**Comment by gfreedncam** [comment]
All good points, and I have included these and others in both the CC and AD sections.
