### ISSUE TITLE
[Accessible Media Tutorial] - quality considerations

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-tutorials#511]
Would add percentage needed for quality to make captions usable - believe this is around 97%.

**Comment by gfreedncam** [comment]
That could be true for real-time captions, but for off-line/pre-produced captions (which is what the tutorial covers), 100% should be the target.  No?

**Comment by James-Green** [comment]
I would agree :)

**Comment by brewerj** [comment]
Geoff added a sentence that for offline captioning, 100% can be achieved.
