### ISSUE TITLE
[Accessible Media Tutorial] Related WCAG 2.0 resources

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-tutorials#513]
Add "Related WCAG 2.0 resources" to each page, e.g.,:
https://www.w3.org/WAI/tutorials/page-structure/regions/#related

**Comment by yatil** [comment]
Note that this can be referenced by SC number/technique ID in the tutorials, I don't think it is needed that we add them in verbatim.

**Comment by brewerj** [comment]
Is it a strong preference of EOWG not to include text of SC, or perhaps handy to have it right in front of the reader? Just checking, before removing these.

**Comment by yatil** [comment]
No, no, no :-) We have SC texts in the tutorials, and they are also in the Accessible Media Tutorial right now. I think this issue is addressed properly.

**Comment by brewerj** [comment]
Geoff & I discussed this; if EOWG has no strong preference, we believe it is more useful to leave the expanded SC text in place.

**Comment by yatil** [comment]
@brewerj Just to clarify: We have expanded SC text, and we appreciate SC text. I asked Geoff not to put the text in verbatim in _his drafts_ as we have a mechanism in place to get the SC text _automatically_ from a file. So there is no need to write out/copy and paste them in the stand-alone drafts, and I wanted to avoid that additional work. (I guess that backfired, considered the discussion. Sorry for not explaining this more clearly.)
