### ISSUE TITLE
Navigation landmark inside main landmark

### ISSUE THREAD

**Issue by jongund** [w3c/wai-tutorials#514]
Why is the left hand navigation landmark inside the main landmark,  When you navigate to the main landmark using a screen header now you have to go through all the right hand side navigation links.

**Comment by mcking65** [comment]
I agree with @jongund, the nav is not main content. 

The name of the nav region is too long:
"On this page   (skip)" sounds so awkward.
I recommend "This Page".

Inside the nav there is a skip link for skipping past the nav ... that is unnecessary if nav is outside main.

The nav also contains a fig with a figcaption that probably shouldn't be there at all; perhaps alt="" if there is some eye candy you want to keep. That figcaption generates a bunch of weird verbosity.

**Comment by yatil** [comment]
The left navigation is part of the tutorial. It points to other parts of the tutorial. “This page navigation” sounds more awkward than “On this page navigation”. The skip link was requested by screen reader users and is in the heading that is referenced by aria-labelledby. I don't think this is urgent, or really relevant for the navigation of the tutorials.

I don't know what the alt="" is referring to. Happy to adopt a pull request, but this sound very nebulous. Also we are working on a new overall website design where the navigation is different and outside the main.
