### ISSUE TITLE
[Accessible Media Tutorial] - turning off automatic captions

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-tutorials#515]
I think this statement, found on https://www.w3.org/2017/04/xsmedia-tute/page3.html, is unclear: While authors cannot prevent YouTube from creating the auto-captions, the captions should always be disabled once the video has been uploaded so that users cannot turn them on. Read the instructions for disabling automatic captions.

Sometimes the auto captions are accurate although usually missing punctuation. I'm not sure they should always be turned off unless you have uploaded a more accurate version.

**Comment by yatil** [comment]
Moved to wai-media-intro repository
