### ISSUE TITLE
[Accessible Media Tutorial] Concepts

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#517]
_(for Last updated: $Date: 2017/05/04 12:42:15 $)_

* Intro sentence talks about Captions, then Audio descriptions. It would be good to tie them together and have a sentence there why Accessible Media as a whole is so important for accessibility.
* “make accessible” is used repetitively
* The list of common methods echoes the first paragraph. Decide for one.
* Under “Quality Considerations”: Better use an active and encouraging wording, “unacceptable” sounds harsh, and it might drive people to imply that no captions/descriptions are better than sub-optimal ones.
* Under why is this important: the paragraph is a bit repetitive of the first section of the page.
* In the list always starts with the people affected. Instead of “Captions are useful when teaching children and adults how to read, or to help people learn a foreign language.” try something like “Children and adults who are learning to read use captions to follow the content of the video, which is especially beneficial when learning a new language.”
* After reading the page I have the general overview, but no concepts of the steps that are necessary for implementing Captions and Audio descriptions. That’s what the first list on every tutorial concepts page does. 
* What is “accessible media?” It is not a concrete term. For me it sounds like this is mostly about videos and a bit audio, but what is with interactive SVGs, infographics, and images?
* It is a bit unclear to me (thinking about it as a reader who has never heard of “accessible media” before) what the goals of the tutorial are and what my next steps are.

**Comment by iamjolly** [comment]
Per @yatil's first bullet in his comment: 
> Intro sentence talks about Captions, then Audio descriptions. It would be good to tie them together and have a sentence there why Accessible Media as a whole is so important for accessibility.

I suggest an edit to the first paragraph to be something like this: 

> Captions and audio descriptions make online media accessible to people who have disabilities. This tutorial will demonstrate how to add captions and audio descriptions for online media. Other accessibility techniques, such as transcripts and foreign-language subtitles, will also be included in the discussion.

The specifics on why we need captions and audio descriptions are covered under the heading "Why is this important?", so some of that language was also removed.

**Comment by brewerj** [comment]
Some of these comments are also being responded to in May 25 updated docs; however, others seem potentially out of scope, such as differentiating this tutorial from SVG etc. Concerned about scope creep.

**Comment by yatil** [comment]
I think most of the issues are addressed. This has been before the thorough review. I am still not too thrilled that we say “media” but mean “audiovisual media” only. However, I think it is OK and clear from the content.
