### ISSUE TITLE
[Accessible Media Tutorial] Production options for captions

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#518]
* “Captions are intended for people who are deaf or hard of hearing.” – Too absolute, there are many other use cases as well.
* “From an authoring standpoint, captions are simply text presented through markup that contains timing information and positioning codes.” – What does that mean from an implementation side? 
* “Captions always reflect dialog and narration, and are always written in the same language as the audio.” – Does that mean that captions in another language than the videos are not captions? Are they subtitles? Can we make this sentence more clear?
* Example of pop-on captions: Show as inline video?
* Example of roll-up captions: Show as inline video?
* “(Live or real-time captions are created on the fly at the time of transmission or broadcast, and require the highly developed skills of trained stenographers. They are not for do-it-yourselfers.)” – “do-it-yourselfers” is too collequal, also that whole parenthesis is unnecessary.
* “For large quantities of material, though, it may be more time and cost efficient to hire a caption agency to produce the captions.” – Do we need that? We also don’t have that on the other tutorials.
* “The basic workflow for pre-produced captions (for playback on desktop or mobile platforms) generally follows this pattern:” – I think the content of the parenthesis is not necessary. It’s for the web. :-)
* The editor image is a bit wide, it might be hard to read the text on it on a small-screen device.
* Styling captions paragraph is very long, what about: “While it is possible to add styling information to captions, the support in browsers varies. If the video is produced for a specific player, style the captions to that player’s capabilities.”
* I don’t feel we must have examples for something that we ultimatively don’t really recommend/is for a specific use case.
* “Automatically generated captions” section can be just a sidebar box linking to page 3.
* Good to link out to resources for writing captions, but it would be good to at least have an overview on the page. It would fit the current scope of the page.

**Comment by brewerj** [comment]
Some of these comments are being addressed in latest files updates coming today 25 May. Please recheck once you're received and posted those.

**Comment by yatil** [comment]
Moved to w3c/wai-media-intro#53.
