### ISSUE TITLE
Tables with multi-level headers Errors?

### ISSUE THREAD

**Issue by Nick2o** [w3c/wai-tutorials#520]
I am studing once again html and css. I found the web page of wai-tutorials and used it for practicing my html table tags and to learn about accesibility. When i was studing the section Tables with multi-level headers, i got confused about the Example 1: Table with multiple column headers in each column (https://www.w3.org/WAI/tutorials/tables/multi-level/). The code seems to be wrong and not complying whit standars. I will do a simple list of problems that i think it have:

- The code of the page itself is not the same as the shown on the snipet. So if you explore the code of the webpage to get the full view it may confuse you.

- The full code example show that a header cell has an attribute headers that relate the header cell whit a blank or empty data cell. Html headers attribute description for th and td say that the values can be only the id of headers cell not table data cell.

```
<tr>
    <td id="blank">&nbsp;</td>                                        // why not just <td></td>
    <th id="co1" headers="blank">Example 1 Ltd</th>
    <th id="co2" headers="blank">Example 2 Co</th>
  </tr>
  <tr>
    <th id="c1" headers="blank">Contact</th>                //why this header has a header td, is not logic
```

For what i get from other sites, when you use the headers attibute you need to put on any td that have data  or is related to a header the headers id like this `<td headers="id1 id2 .....">` and all th  must have an id and u cant use scope. I am not sure about the scope atribute in the headers, for example if the row relation is clear can i just use scope = row and in the cell add the id for the columns headers. Well it does not seem logic when i think of it (headers could overwrite the scope = row). It would be nice to add an explanation about it on the web page so people will not get confused. I hope it is clear, english is not my first language.

**Comment by yatil** [comment]
> The code seems to be wrong and not complying whit standars.

Interestingly the validator is annoyed by `<td id="blank">&nbsp;</td>` not being a `<th>`. The technique used to be valid in HTML4/XHTML and got carried over in the tutorial. Thanks for finding this!

> The code of the page itself is not the same as the shown on the snipet. So if you explore the code of the webpage to get the full view it may confuse you.

We wanted to point out the interesting bits of the code. There is a link to the [full code example](https://www.w3.org/WAI/tutorials/tables/examples/multiplecolumnheaders/). The code in the sample and the snippet are the same.

> The full code example show that a header cell has an attribute headers that relate the header cell whit a blank or empty data cell. Html headers attribute description for th and td say that the values can be only the id of headers cell not table data cell.

See above :-)

> ```html
> <tr>
>     <td id="blank">&nbsp;</td>                                        // why not just <td></td>
>     <th id="co1" headers="blank">Example 1 Ltd</th>
>     <th id="co2" headers="blank">Example 2 Co</th>
>   </tr>
>   <tr>
>     <th id="c1" headers="blank">Contact</th>                //why this header has a header td, is not logic
> ```

While it might not seem to be logic, a screen reader would read “Example 1 Ltd” as the heading for “Example 2 Co” and the “Contact/Position/Email” headers on the left would be headings for themselves. With the headers="blank" we basically say “This cell has no headers.”

> For what i get from other sites, when you use the headers attibute you need to put on any td that have data or is related to a header the headers id like this `<td headers="id1 id2 .....">` and all th must have an id and u cant use scope. I am not sure about the scope atribute in the headers, for example if the row relation is clear can i just use scope = row and in the cell add the id for the columns headers. Well it does not seem logic when i think of it (headers could overwrite the scope = row). It would be nice to add an explanation about it on the web page so people will not get confused.

Indeed there are some use cases where scope might be sufficient. When you have multiple tables in one, like on this page, it does not. For guidance on how/when to use scope, see: https://www.w3.org/WAI/tutorials/tables/irregular/

**Comment by Nick2o** [comment]
I still think that the code of the snipet and the code of the source code of the web page and the full code example are different. The full example code is the same as the one in the source code of the web page .

the code on the snipet

```
CODE SNIPPET: ASSIGNING ID ATTRIBUTES TO <TH> CELLS
[…]
<th id="co1">Example 1 Ltd</th>                                      //here is the difference
<th id="co2">Example 2 Co</th>                                      //here is the difference
[…]
<th id="c1">Contact</th>                                                  //here is the difference
[…]

CODE SNIPPET: ASSIGNING HEADER ATTRIBUTES TO <TD> CELLS
[…]
<td headers="co1 c1">James Phillips</td>
<td headers="co2 c1">Marie Beauchamp</td>
[…]
```
the code of the full example

```
<tr>
    <td id="blank">&nbsp;</td>
    <th id="co1" headers="blank">Example 1 Ltd</th>    //here is the difference
    <th id="co2" headers="blank">Example 2 Co</th>    //here is the difference
  </tr>
  <tr>
    <th id="c1" headers="blank">Contact</th>                //here the difference
    <td headers="co1 c1">James Phillips</td>
    <td headers="co2 c1">Marie Beauchamp</td>
```

From the snipet i could think that contact (and the others headers) being a header but not related to any other headers, it does not need to have an attribute headers. From the full code exaple what i get is that even headers (th) need to have a headers attribute to a Blank/Void cell. The problem is that the two codes give different messages or say two different things what may confuse. Actually i am not sure what to do if i have a table like this. Probably i will not make the blank cell a header cell and i will not add a headers attribute for the headers of the rows (Contact, Position and Email) or columns (Example 1 Ltd and Example 2 Co). Since i am no expert on this how can i really know what to do?, that is the main reason of the issue to clarify what is the right approach. I was looking for a screen reader to test myself but there were the paid ones (i am not planing to buy any) and the free ones make my antivirus go crazy.

**Comment by yatil** [comment]
Hi @Nick2o,

You’re right. We’re gonna fix that asap. (I think the example is not too clear overall, so we need to put a bit of effort in it.)

The only screen reader that is free on Windows is [NVDA](https://www.nvaccess.org), there are screen readers for Android and built-in in iOS/Mac. There are free options on Linux as well. Newer versions of Windows have [Narrator built-in](https://en.wikipedia.org/wiki/Microsoft_Narrator).

**Comment by Nick2o** [comment]
Hi @yatil,

Well i will try NVDA even whit the warning from Chrome, after all it will not be the worst thing that i will install on my pc XD and probably Win 10 is worse. Thanks for your response i will try to check later on the tutorials, keep the good work.

**Comment by rbenson** [comment]
@yatil - this may be another issue, but yesterday on WebAIM there was a thread [about scopes vs IDs](http://webaim.org/discussion/mail_thread?thread=8163). Jonathan made the claim that using `scope` on tables was fine as long as a cell has 3 or less headers applied to it. Should the tutorials address this?

**Comment by yatil** [comment]
@rbenson Just seeing your comment:

We did test it and run into different problems with scopes and three headings (I don’t recall details, and it was more confusing than inaccessible iirc). For the sake of clarity and ease of teaching different use cases, we opted to draw pretty strict lines in the sand here.

**Comment by rbenson** [comment]
@yatil +1. I am more in favor of adding ` headers` vs assuming AT figures it out
