### ISSUE TITLE
[Fly-out Menus] nav has role="presentation"

### ISSUE THREAD

**Issue by robfentress** [w3c/wai-tutorials#523]
Based on [NU HTML Checker report](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.w3.org%2FWAI%2Ftutorials%2Fmenus%2Fflyout%2F) (Other instances of this error, and others, as well):

<p><strong>Error</strong>: <span>Bad value <code>presentation</code> for attribute <code>role</code> on element <a href="http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-nav-element"><code>nav</code></a>.</span></p><p class="location">From line <span class="first-line">254</span>, column <span class="first-col">1</span>; to line <span class="last-line">254</span>, column <span class="last-col">76</span></p><p class="extract"><code>content"&gt;<span class="lf" title="Line break">↩</span><b>&lt;nav role="presentation" aria-label="Main Navigation" id="flyoutnavkbfixed"&gt;</b><span class="lf" title="Line break">↩</span>		&lt;ul</code></p>

**Comment by yatil** [comment]
This is done so that screen readers and other technologies don’t pick up the **Examples** as actual navigations. `role="presentation"` is built exactly for that use case.
