### ISSUE TITLE
[Fly-out Menus] style tag not allowed in body

### ISSUE THREAD

**Issue by robfentress** [w3c/wai-tutorials#524]
Based on [NU HTML Checker report](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.w3.org%2FWAI%2Ftutorials%2Fmenus%2Fflyout%2F) (Other instances of this error, and others, as well):

> Error: **Element style not allowed as child of element div in this context. (Suppressing further errors from this subtree.)**
> 
> From line 136, column 1; to line 136, column 7
> 
> `>↩</nav>↩↩<style>↩.show`
> 
> Contexts in which element style may be used:
> 
> - Where metadata content is expected.
> - In a noscript element that is a child of a head element.
> 
> Content model for element div:
> 
> - If the element is a child of a dl element: one or more dt elements followed by one or more dd elements, optionally intermixed with script-supporting elements.
> - If the element is not a child of a dl element: Flow content.

**Comment by yatil** [comment]
We are aware of that, but for practical reasons, it makes sense to have the example styling inline instead of having it externally. We know that this is sub-optimal, but it works in browsers and makes our files easier maintainable. We might revisit this issue at some time.
