### ISSUE TITLE
[Fly-out Menus] update aria states on mouseover and mouseout events as well

### ISSUE THREAD

**Issue by robfentress** [w3c/wai-tutorials#525]
For the [fly-out menu tutorial examples](https://www.w3.org/WAI/tutorials/menus/flyout/), shouldn't the ARIA states be updated on the mouseover and mouseout events as well?

**Comment by yatil** [comment]
Interesting idea – would that be picked up by any assistive technology? (I don’t think it makes a difference, more semantics is _always_ good, but I wonder.)

**Comment by robfentress** [comment]
I guess I'm just thinking about whether some populations might be using both a mouse and a screen reader in some instances, so I worry the state might get out of sync, if you don't deal with that.  Haven't really dug into it and explored the consequences, but it occurred to me.

**Comment by yatil** [comment]
Hi, @robfentress, would you like to take a look at the Approach 2 here and confirm that this works as you’d expect? 

https://w3c.github.io/wai-tutorials/menus/flyout/#use-button-as-toggle

**Comment by sharronrush** [comment]
Eric suggested good approach, no objection from commenter, closed
