### ISSUE TITLE
Suggest new name for Nav region

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-tutorials#546]
<nav aria-label="Main Navigation">
will get confused with <main> and "navigation" is already spoken by role

Suggest "primary" or something else

**Comment by mcking65** [comment]
I believe nav region labels are most helpful when they say what is being navigated or what the purpose of the set of links is. "Primary" does not do that.

Could you provide a link to the page that contains that nav region that you are suggesting needs to be renamed so we can see the context?

**Comment by yatil** [comment]
Hi @DavidMacDonald, a link to the page would indeed help.

* [ ] FWIW, I think this example should have the label “Main” instead of “Main Navigation”: https://www.w3.org/WAI/tutorials/page-structure/regions/#navigation
* [ ] Same goes for here: https://www.w3.org/WAI/tutorials/page-structure/labels/
* [ ] We should probably use the same examples on both pages…
* [ ] Also align the full example: https://www.w3.org/WAI/tutorials/page-structure/example/

**Comment by yatil** [comment]
Hi @mcking65, can you put that thought into a different issue? Otherwise, it is hard to keep track. Thank you!

**Comment by mcking65** [comment]
Definitely. I raised two separate issues. Sorry for creating unnecessary clutter and distraction in this one. I will now trim my comment to what is only relevant for this issue.

**Comment by yatil** [comment]
Thanks @mcking65!

**Comment by DavidMacDonald** [comment]
I think it might be confusing to label something "main navigation" or 
`<nav aria-label="main">...`
It might become confused with 
`<main>`
Region...
There may be a better label than 
`<nav aria-label="primary">...`
but that's the best I can come up with.

**Comment by yatil** [comment]
I slightly prefered main navigation to primary, but your point colliding with the main region is a valid point.

**Comment by shawna-slh** [comment]
Good news: We have an update editor working on the Tutorials! Brian Elton

He's prepared a pull request for this issue: https://github.com/w3c/wai-tutorials/pull/682

If anyone is up for reviewing that and +1ing or commenting, we would appreciate your contribution!

**Comment by brianelton** [comment]
Closing as per #682
