### ISSUE TITLE
Tutorial Site Design: Move breadcrumbs and "On this page" outside main region, consider eliminating "On this page"

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-tutorials#548]
Based on the rationale I provided is issue #547, change the tutorial site design so that the main landmark region contains only the main content. Move nav regions outside of main.

Also consider whether the site design could be made simpler and cleaner by eliminating the "on this page' nav region. For such short pages, it doesn't provide any significant utility, and thus feels like clutter ... just something you have to skip past when reading. It especially feels that way for me as a screen reader user.

**Comment by yatil** [comment]
Thanks for your input. We are currently working on the big WAI redesign, and the tutorials will be available for preview in the new design soon. I am looking forward to your feedback then, too! 

We specifically talked about the “Page Contents” section and we are keeping it, for now, I think. The overview is useful for non-screen reader users as they do not have the possibility to summon a list of headings. As it is a navigation that reflects the main content, I think semantically the right thing is to have it in the `main` element, too.

In the current tutorial design, you can skip the navigation.

I see that this can be a highly personal topic, and every user has different needs and preferences. Maybe we can look into personalization options for the new WAI site where people can switch on/off Table of Contents.

(@slhenry FYI.)

**Comment by shawna-slh** [comment]
moot with redesign
