### ISSUE TITLE
Use of uppercase letters for link text in header

### ISSUE THREAD

**Issue by srinivasuchakravarthula** [w3c/wai-tutorials#550]
As we normally don't recommend use of `<uppercase>` for things other than abbreviations, I think we should change link text of "Get Involved" and "About W3C WAI (ABOUT world)" to none. This improves readability.

**Comment by yatil** [comment]
This issue was moved to w3c/wai-website#23

**Comment by yatil** [comment]
Hi @srinivasuchakravarthula, I moved this general issue to the general repository. Thanks for your feedback.
