### ISSUE TITLE
Fly-out Menus Approach 1

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-tutorials#559]
From e-mail to wai@w3.org:

Thank you very much for providing the WAI tutorials. I find them very helpful when providing feedback about web accessibility to those web developers who know little about accessibility.

 

On the "[Approach 1 : Use parent as toggle](https://www.w3.org/WAI/tutorials/menus/flyout/#use-parent-as-toggle)" example, I find, with multiple browsers and screen readers, that the "expanded" or "collapsed" state is not always correct:

 

    Press Enter or Space on "Space Bears" to expand it.
    Navigate to another menu item (such as "Mars Cars") or switch to another application and back again) to close the menu.
    The state of the "Space Bears" menu is still "expanded", despite the menu being collapsed (at least for a screen reader user).

 

Also, it might be helpful to make the example for mouse users work for keyboard users too.

 

I hope that this helps, but please tell me if you need further details.

**Comment by yatil** [comment]
When navigating from the opened fly out menu to one of the other main navigation items, the menu closes but `aria-expanded` is not reset to `false`.
