### ISSUE TITLE
Tutorials Overview

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-tutorials#568]
These links are still on the Overview page.  Should they be updated too?  Or the new links to new resources put in?

- Web Content Accessibility Guidelines (WCAG) 2.0 Overview : Introduces the international standard that defines requirements on how to make web content more accessible to people with disabilities

- Authoring Tool Accessibility Guidelines (ATAG) 2.0 Overview : Introduces the international standard that defines requirements on how to make web authoring tools that support accessibility for people with disabilities

**Comment by yatil** [comment]
Thanks, @kakinney, what would I do without you! 

I think both links can lose the 2.0 as the titles of the pages don’t have it. I’ll make sure to update the page before publication.
