### ISSUE TITLE
Question regarding WCAG 2.0, WCAG 2.1, and WCAG 2

### ISSUE THREAD

**Issue by nrhsinclair** [w3c/wai-tutorials#569]
I find this labeling a bit confusing. WCAG 2 could cause confusion, looks as though 2.1 is not included in 2

**Comment by slhenry** [comment]
This is an open issue site-wide. Hopefully we'll get it addressed in Sept...

**Comment by yatil** [comment]
We will use “WCAG” (no version number) when it is insignificant if WCAG 2.0 or 2.1 is meant. (WCAG 1 is in the process of being marked obsolete.)
