### ISSUE TITLE
 Complete “Table with header cells in the top row only” Code Example has no scope attributes

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/wai-tutorials#574]
the complete code example https://www.w3.org/WAI/tutorials/tables/examples/headertoprowfirstcol/ for the tutorial example https://www.w3.org/WAI/tutorials/tables/two-headers/#table-with-header-cells-in-the-top-row-and-first-column does not include the `scope` attributes.

also the Back to the example link https://www.w3.org/WAI/tutorials/tables/examples/simple.html#table-with-header-cells-in-the-top-row-and-first-column is broken

**Comment by yatil** [comment]
Thanks! I’m going to fix it!
