### ISSUE TITLE
Where is the mouse-disabled form

### ISSUE THREAD

**Issue by Stefany93** [w3c/wai-tutorials#575]
Guys, I am making a presentation and I am looking for that airplane ticket booking example form where the mouse events are disabled and you can only fill it in with a keyboard. I really want to show it off to my audience to help them understand what an accessible form is. Thanks!

**Comment by yatil** [comment]
Hi, we don’t have an example for this. I think just telling your audience to not use the mouse should be sufficient to demonstrate it. (We don’t want to show bad examples and removing mouse input would be bad for many users :-D)

**Comment by slhenry** [comment]
Hi Stefany,

You are welcome to send this question to the public WAI Interest Group (WAI IG) Discussion List.

You can search the mailing list archives, to get a feel for the list, through:
	http://lists.w3.org/Archives/Public/w3c-wai-ig/

You can join the mailing list and post questions by following the instructions about the Discussion List under:
	https://www.w3.org/WAI/about/groups/waiig/#mailinglist

~Shawn
