### ISSUE TITLE
Tables with multiple column headers -NVDA/Chrome, Narrator/Edge and VO/Safari 

### ISSUE THREAD

**Issue by shirsha** [w3c/wai-tutorials#588]
I am looking at  "Example 2:  Table with three headers related to each data cell" in
**https://www.w3.org/WAI/tutorials/tables/multi-level/**

It is working as expected  with JAWS/IE, JAWS/Chrome  and  NVDA/FF.
But It is not working fine in the following screenreader/browser combination.
•	With NVDA/Chrome, it is narrating each datacell with both headers i.e Paris Rome followed by the value in the data cell, instead of narrating one header.
•	With VO/Safari and Narrator/Edge, the extra header i.e "Paris" or "Rome" is not narrated with the data cell.

I don't see an issue with the code.
I suspect that this is a screen reader/browser compatibility issue. 
Has anybody encountered this issue? Any information on this will be really helpful.
Please see the attached screenshot of the table.
[Multi header table.docx](https://github.com/w3c/wai-tutorials/files/3315391/Multi.header.table.docx)

**Comment by yatil** [comment]
Image of the table, extracted from the .docx in original comment:
<img width="447" alt="image1" src="https://user-images.githubusercontent.com/58862/64521743-dc39ab00-d2f8-11e9-9c9a-29897fea041d.png">

**Comment by yatil** [comment]
@shirsha I think some screen readers only read all headers when you explicitly ask for the headers. It is one reason why we try to strongly suggest splitting up complex tables like this.
