### ISSUE TITLE
Description for header and footer not correct

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wai-tutorials#590]
https://www.w3.org/WAI/tutorials/page-structure/regions: 
"If the header/footer element is used inside article and section elements, it is not associated with the whole page, but only with that specific article or section."

https://w3c.github.io/html-aam/:
"scoped to the body element: ... / scoped to the main element, a sectioning content element, or a sectioning root element other than body"

https://github.com/w3c/html-aria:
"If not a descendant of an article, aside, main, nav or section element role=..., otherwise No corresponding role"

https://w3c.github.io/aria-practices/#html-sectioning-elements:
"banner/contentinfo when in context of the body element"

See also: https://github.com/w3c/html-aria/issues/161

**Comment by yatil** [comment]
The tutorial deliberately does not go into details of sectioning content and sectioning roots and tries to simplify for broad cases instead of specific technical detail, in an attempt to be more clear and straight-forward.

That said, I think the scoping related to the main element warrants a mention (I am pretty certain it was introduced after the publication of the tutorials), as well as a link to detailed technical explanations.

**Comment by JAWS-test** [comment]
I agree that explanations about sectioning content and sectioning root in the tutorial are not relevant, but the information "If the header/footer element is used inside article and section elements, it is not associated with the whole page, but only with that specific article or section" is wrong because inside article and section header and footer are not output

**Comment by yatil** [comment]
Can you specify what you mean by “are not output”? They are semantically attached to the article and section. They don’t have any specific ARIA set (and so it is up to assistive technology to announce it or not), but that does not change the underlying semantics.

**Comment by JAWS-test** [comment]
@yatil: “are not output” means that within article and section header and footer have no meaning, since they are delivered by the browser without role to the Accessible Interface and are therefore output without role by assistive technology. 

If I read: "If the header/footer element is used inside article and section elements, it is not associated with the whole page, but only with that specific article or section." it is suggested to me that header and footer can be used sensibly within article and section. But this is not the case. 

> and so it is up to assistive technology to announce it or not

According to HTML AAM, it is not up to assistive technology to decide what happens with header and footer within article and section. It should be output as text and not as header or footer. And so it is (except for Firefox, which doesn't follow the specification: https://github.com/FreedomScientific/VFO-standards-support/issues/216). 

If the explanation about header and footer is about what the element refers to (independent of assistive technology), then the statement is correct, but not complete, because this is not only true for article and section, but for all sectioning content or sectioning root elements. However, this information is irrelevant and misleading in a tutorial about accessibility (as explained above).

**Comment by yatil** [comment]
Thanks for the clarification.

**Comment by yatil** [comment]
Again, thanks for the clarification. However I think that having a semantic correlation is still valid to mention. Assistive technology could decide to make certain headers and footers available to their users, if they find it useful.

I’ll try to find a more clear description.
