### ISSUE TITLE
Contributing translations

### ISSUE THREAD

**Issue by rotnicki** [w3c/wai-tutorials#595]
I would like to comtrubute Polish translation of the WAI Tutorial.
What is the proper and best way to do it?

**Comment by slhenry** [comment]
Hi @rotnicki 

Thank you for your interest in providing translation of the WAI tutorials.

Information about translating WAI resources is at: https://www.w3.org/WAI/about/translating/

The tutorials are not ready for translation yet. We expect they will be in the coming months.

In the meantime, would you be interested in translating other [resources listed on that page under Priorities...](https://www.w3.org/WAI/about/translating/#priorities)?

A good resource to start with is [Video Introduction to Web Accessibility and W3C Standards](https://www.w3.org/WAI/videos/standards-and-benefits/)

Feel free to e-mail me directly if you have other questions: shawn@w3.org

Thanks!
~[Shawn](https://www.w3.org/People/Shawn/)

**Comment by slhenry** [comment]
(Leaving issue open for when they are ready for translation...)

**Comment by yatil** [comment]
@rotnicki Thanks for your interest. The tutorials have many open issues and need to be brought into the new site design so you and other translators can work with our translation process. Significant portions of the tutorials can also benefit from updates, so any translation at this point in time would be outdated really soon. We’ll keep you posted when those updates have happened.

**Comment by rotnicki** [comment]
> We’ll keep you posted when those updates have happened.

@yatil has anything happened since then?

**Comment by brianelton** [comment]
Hi @rotnicki - unfortunately the Tutorials section has not had a ton of work done on it until recently. I am trying to work through the PRs and issues and hopefully will have things up to date soon.

**Comment by rotnicki** [comment]
Yes I am interrested primarely in translating "An alt Decision Tree" as it is a kind of "first aid kit" when providing advice to people creating content that icludes images. The always ask me how to create "good" alternative text?

BTW: I also tried to figure out how to compile a complete web site from source files in this wai-tutorials repository? Is there any documentation on how to do it?

**Comment by shawna-slh** [comment]
> Yes I am interested primarely in translating "An alt Decision Tree"

Good to know, I created an issue https://github.com/w3c/wai-tutorials/issues/713

> Is there any documentation on how to do it?

Not specifically.

**Comment by remibetin** [comment]
_An Alt Decision Tree_ is now ready for translation! 🚀 

@rotnicki Are you still interesting in contributing to the Polish translation of this page? In case, an ongoing Polish translation is welcoming reviews: https://github.com/w3c/wai-tutorials/pull/786

If you are interested, you can find guidance on reviewing translations at: https://www.w3.org/WAI/about/translating/reviewing/

Let me know what you think. I can provide further help.
