### ISSUE TITLE
ARIA-haspopup not valid for flyout use case in ARIA 1.1

### ISSUE THREAD

**Issue by yatil** [w3c/wai-tutorials#611]
In  https://www.w3.org/WAI/tutorials/menus/flyout/ the guidance around ARIA-haspopup needs to be removed as it does not apply to non-aria-menu navigations anymore in ARIA 1.1:

ARIA 1.0: https://www.w3.org/TR/wai-aria-1.0/states_and_properties#aria-haspopup
ARIA 1.1: https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup

It is however backwards compatible: “To provide backward compatibility with ARIA 1.0 content, user agents MUST treat an aria-haspopup value of true as equivalent to a value of menu.”

**Comment by JAWS-test** [comment]
I think aria-haspopup would have to be removed because it is no longer allowed on a link: https://rawgit.com/w3c/aria/master/#aria-haspopup

**Comment by yatil** [comment]
That, too. Such a shame, it was really useful to indicate that something would happen :-/

**Comment by brianelton** [comment]
aria-haspopup was removed in PR #633
