### ISSUE TITLE
The term "full-text equivalent"

### ISSUE THREAD

**Issue by MakotoUeki** [w3c/wai-tutorials#629]
Images Concepts
https://www.w3.org/WAI/tutorials/images/

The 5th bullet about "Complex images such as graphs and diagrams" reads "To convey data or detailed information, provide a full-text equivalent of the data or information provided in the image as the text alternative."

The term "full-text equivalent" is unclear. Does this mean "text-only equivalent"? Or does it mean that the text alternative should present all data or text in the image?

This is a question from the Alt Text sub-group of the Silver task force. We're reviewing the Tutorials to create some Method documents for WCAG 3.0. Thanks!

**Comment by yatil** [comment]
I think that should be a “full text equivalent”, so:

> Or does it mean that the text alternative should present all data or text in the image?
