### ISSUE TITLE
Tutorials: Links under "Additional Resources" result in 404

### ISSUE THREAD

**Issue by jmuheim** [w3c/wai-tutorials#634]
The links under `Additional Resources` (https://wai-tutorials.netlify.app/tutorials/) all result in 404:

- How People with Disabilities Use the Web (https://wai-tutorials.netlify.app/people-use-web/)
- Accessibility Principles (https://wai-tutorials.netlify.app/fundamentals/accessibility-principles/)
- Web Content Accessibility Guidelines (WCAG) Overview (https://wai-tutorials.netlify.app/standards-guidelines/wcag/)
- Authoring Tool Accessibility Guidelines (ATAG) Overview (https://wai-tutorials.netlify.app/standards-guidelines/atag/)

**Comment by jmuheim** [comment]
Actually, many more links do:

- https://wai-tutorials.netlify.app/fundamentals/accessibility-intro/
- https://wai-tutorials.netlify.app/test-evaluate/
- Many more

Actually, pretty much everything outside https://wai-tutorials.netlify.app/tutorials/ results in 404. 😦

**Comment by yatil** [comment]
Yes, this is by design. The preview only renders the pages that belong to the tutorials, not other pages on the W3C/WAI website. The released version of the tutorials can be found here and should not feature any broken links: https://w3.org/WAI/tutorials

**Comment by jmuheim** [comment]
I understand, sorry for the confusion. Thank you!
