### ISSUE TITLE
[Based on deployed Pull Request] Menu Bug

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-tutorials#637]
@yatil - Found menu bug in deployed pull request <https://wai-tutorials2.netlify.app/tutorials/>

When selecting one of the tutorials from the left navigation, and then selecting a page in that tutorial, all of the pages for all tutorials are expanded in the menu.

**Comment by yatil** [comment]
@bakkenb I know. As I have said yesterday in the meeting, something did not come through. Will fix asap.

**Comment by yatil** [comment]
Fixed! (Shawn had merged a PR from me that fixed the navigation, and I basically diverged from an earlier point for my later Pull Request. My bad! Probably need to fix it elsewhere, too!)

**Comment by yatil** [comment]
Also fixed in this Pull Request for the main WAI site: https://github.com/w3c/wai-website-data/pull/81
