### ISSUE TITLE
removing summary attribute content

### ISSUE THREAD

**Issue by fstrr** [w3c/wai-tutorials#659]
Hi

AGWG is planning to remove [H73](https://www.w3.org/WAI/WCAG21/Techniques/html/H73.html) (Using the summary attribute of the table element to give an overview of data tables) because the `summary` attribute is obsolete in HTML. H73, and an example of using the `summary` attribute, are included in the [Captions And Summary page](https://www.w3.org/WAI/tutorials/tables/caption-summary/#using-the-summary-attribute), which will need to be updated. See the [WCAG old techniques to remove](https://github.com/w3c/wcag/issues/2482) issue.

Thanks

**Comment by yatil** [comment]
@fstrr I created a pull request for this.

**Comment by fstrr** [comment]
@yatil Thanks :)
