### ISSUE TITLE
Incorrect previous and next buttons 

### ISSUE THREAD

**Issue by joppekroon** [w3c/wai-tutorials#666]
The next button of the "[Multi-Page form](https://www.w3.org/WAI/tutorials/forms/multi-page/)" and "[Custom controls ](https://www.w3.org/WAI/tutorials/forms/custom-controls/)" pages, point to themselves. The previous button on these pages both point to "Validating Input".

**Comment by remibetin** [comment]
I am closing this issue that has been fixed by https://github.com/w3c/wai-tutorials/pull/672
