### ISSUE TITLE
Next button is not working correctly

### ISSUE THREAD

**Issue by bappyasif** [w3c/wai-tutorials#689]
next button at this tutorial is not functioning properly, it keeps showing same page over and over

https://www.w3.org/WAI/tutorials/images/groups/

![image](https://user-images.githubusercontent.com/19854521/189488711-80146b96-b5e2-41f2-a19b-28ae4ca84a54.png)

**Comment by brianelton** [comment]
fixing in #691

**Comment by brianelton** [comment]
Issue fixed
