### ISSUE TITLE
Table with no headers

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/wai-tutorials#702]
Hi,
we are working on an ebook where there are many tables, all with the same structure, to list many products from different suppliers.

In the print version of the book, the tables are without headings, and in the digital version the publisher would like them without headings as well.

How to make them accessible? In the tutorials we do not find a solution to use.

We found this solution, but we are not sure if it is correct. it seems to work well with screenreaders...

```
<table>
	<tr>
		<td aria-label="code">123</td>
		<td aria-label="product name">Product A</td>
		<td aria-label="quality">superior</td>
		<td aria-label="price">4 €</td>
	</tr>
	<tr>
		<td aria-label="code">567</td>
		<td aria-label="product name">Product B</td>
		<td aria-label="quality">superior</td>
		<td aria-label="price">5 €</td>
	</tr>
</table>
```

**Comment by brianelton** [comment]
Your table needs to have `<th>` elements so that it is identified as a data table by screen readers and properly associates the headers with the data. Using `aria-label` on the individual cells will not work.
Add a row of column headers and then hide them visually:
```
<table>
  <tr class="visually-hidden">
    <th>code</th>
    <th>product name</th>   
    <th>quality</th>
    <th>price</th>
  </tr>
  <tr>
    <td>123</td>
    <td>Product A</td>
    <td>superior</td>
    <td>4 €</td>
  </tr>
  <tr>
    <td>567</td>
    <td>Product B</td>
    <td>superior</td>
    <td>5 €</td>
  </tr>
</table>
```
```
.visually-hidden {
    clip: rect(0 0 0 0);
    clip-path: inset(50%);
    height: 1px;
    overflow: hidden;
    position: absolute;
    white-space: nowrap;
}
```
