### ISSUE TITLE
alt Decision Tree for translation

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-tutorials#713]
[An alt Decision Tree](https://www.w3.org/WAI/tutorials/images/decision-tree/) is a popular page. Let's put it high on the list for review and updating if needed. Then open it up for translation (e.g., https://github.com/w3c/wai-website/issues/638 )

**Comment by remibetin** [comment]
@shawna-slh I am closing this issue: _An alt Decision Tree_ has been made ready for translation some months ago, and 5 translations are available to date 🥳
