### ISSUE TITLE
Progress bar examples don't meet non-text contrast requirements

### ISSUE THREAD

**Issue by voidloaf** [w3c/wai-tutorials#731]
There are progress bar examples on this page for [multi-page forms](https://www.w3.org/WAI/tutorials/forms/multi-page/). The progress bars shown under "Using the HTML5 progress element" don't meet the 3:1 contrast with adjacent colors (the green that communicates the percentage, and the blue background that communicates the whole). Can we update this example to meet 3:1 contrast?

<img width="326" alt="Screenshot 2023-11-06 at 12 19 59 PM" src="https://github.com/w3c/wai-tutorials/assets/76041817/beb3faee-5a9a-4a01-a0af-dd5423fec889">

**Comment by remibetin** [comment]
I am closing this issue that has been fixed by https://github.com/w3c/wai-tutorials/pull/732: the example has been updated in November 2023 to meet the 3:1 contrast. 

See https://www.w3.org/WAI/tutorials/forms/multi-page/
