### ISSUE TITLE
Alt decision tree: link text different from destination page title

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-tutorials#753]
from https://github.com/w3c/wai-tutorials/pull/752/files#r1500236491

In https://www.w3.org/WAI/tutorials/images/decision-tree/

_The original text says "Image Concepts Page" in the link text, but the destination of the link was actually "Images Tutorial"._

@brianelton Is that on purpose?

**Comment by brianelton** [comment]
I don't know if there used to be an "Image Concepts Page" that is no longer. @shawna-slh do you have any insight to this?

**Comment by shawna-slh** [comment]
I think the first page was once called "Image Concepts Page" and that changed. May have the same issue on all the other tutorials, too?

**Comment by remibetin** [comment]
Indeed, the title was "Images Concepts" in a previous version (see `master` branch) : https://github.com/w3c/wai-tutorials/blob/master/source/images/index.html.erb.md?plain=1

But in `master-2.0` branch, the title is "Images Tutorials" since the initial commit in 2020. See https://github.com/w3c/wai-tutorials/commit/71c9d15072a0fa640cc9243768891b08f04b1fc4#diff-32c561ff27d222faaf45c6991ebe86150e3fd5cea6c5587a06ac5a8443bd8ec3

**Comment by remibetin** [comment]
I have opened a PR to fix this: https://github.com/w3c/wai-tutorials/pull/774

I have not found other occurrences of "Image Concepts" used as link text in the Tutorials.

**Comment by remibetin** [comment]
Fixed by https://github.com/w3c/wai-tutorials/pull/774
