### ISSUE TITLE
[Japanese] There is no name as contributors on alt decision tree

### ISSUE THREAD

**Issue by hiroya-uga** [w3c/wai-tutorials#756]
- Related PR: #752 
- Page: https://www.w3.org/WAI/tutorials/images/decision-tree/ja

## As-Is

> 翻訳者 Hiroya UGA. 寄稿者 .

## Expected

> 翻訳者 Hiroya UGA. 寄稿者 Naoki Nakamura.

**Comment by hiroya-uga** [comment]
@remibetin cc: @momdo 
Thank you for publishing #752!
But I found a problem.

There is no name as contributors 😭
<img width="1096" alt="image" src="https://github.com/w3c/wai-tutorials/assets/46584540/94e69924-5442-44a9-b1aa-35e05a7d87c5">

**Comment by remibetin** [comment]
Oh I see. This is a problem on our side. I will investigate and fix ASAP.

Thanks for noticing!

**Comment by remibetin** [comment]
@hiroya-uga I expect the clean fix to take some time. 

Since we want to acknowledge @momdo's contribution now, I have opened a PR that does the trick in the meantime: https://github.com/w3c/wai-tutorials/pull/757

**Comment by remibetin** [comment]
@hiroya-uga We have just published the quick fix to acknowledge @momdo's contribution! 🎉 

See https://www.w3.org/WAI/tutorials/images/decision-tree/ja

I am closing this issue, and I have opened [another one](https://github.com/w3c/wai-translations/issues/190) to do the clean fix later.

**Comment by remibetin** [comment]
@hiroya-uga @momdo FYI, I have resolved the other issue: https://github.com/w3c/wai-translations/issues/190
